import type { DemoContent } from "./types";

const content: DemoContent = {
  meta: {
    siteTitle: "Portail national des services publics",
    tagline: "Vos démarches administratives, simplement.",
    entity: "Ministère de la Transition Numérique et de la Réforme de l'Administration",
    description:
      "Portail officiel des démarches et services publics du Royaume du Maroc : état civil, identité, véhicules, impôts, santé, éducation, emploi et logement.",
    officialBanner: "Un site officiel du Royaume du Maroc",
    demoNotice: "Démonstration indépendante : ce portail fictif illustre le système de design DSM. Ce n'est pas un site officiel et aucune donnée n'est transmise.",
    demoNoticeLink: "Découvrir DSM",
  },
  nav: [
    { label: "Accueil", href: "/" },
    {
      label: "Démarches",
      href: "/demarches",
      children: [
        { label: "État civil", href: "/demarches?theme=etat-civil", description: "Naissance, mariage, décès, livret de famille" },
        { label: "Identité & voyage", href: "/demarches?theme=identite-voyage", description: "CNIE, passeport, carte de séjour" },
        { label: "Véhicules & permis", href: "/demarches?theme=vehicules-permis", description: "Immatriculation, permis de conduire, contrôle technique" },
        { label: "Impôts & taxes", href: "/demarches?theme=impots-taxes", description: "Déclarations, paiements et attestations fiscales" },
        { label: "Santé & protection sociale", href: "/demarches?theme=sante-protection-sociale", description: "AMO, CNSS, carnet de santé" },
        { label: "Éducation", href: "/demarches?theme=education", description: "Inscriptions, bourses, équivalences de diplômes" },
        { label: "Emploi & entreprise", href: "/demarches?theme=emploi-entreprise", description: "Création d'entreprise, recrutement, formation" },
        { label: "Logement & urbanisme", href: "/demarches?theme=logement-urbanisme", description: "Permis de construire, titres fonciers, aides au logement" },
      ],
      featured: {
        title: "Extrait d'acte de naissance en ligne",
        text: "Obtenez votre extrait d'acte de naissance signé électroniquement, sans vous déplacer.",
        href: "/demarches/acte-de-naissance",
        cta: "Faire ma demande",
      },
    },
    { label: "Institutions", href: "/institutions/ministere" },
    { label: "Actualités", href: "/actualites" },
    { label: "Aide", href: "/aide" },
  ],
  common: {
    home: "Accueil",
    allServices: "Tous les services",
    seeAll: "Voir tout",
    readMore: "Lire la suite",
    startProcedure: "Commencer la démarche",
    online: "En ligne",
    free: "Gratuit",
    paid: "Payant",
    duration: "Délai",
    updatedOn: "Mis à jour le",
    share: "Partager",
    print: "Imprimer",
    helpTitle: "Besoin d'aide ?",
    helpText: "Nos conseillers vous accompagnent dans vos démarches administratives.",
    helpCta: "Contacter l'assistance",
    contact: "Contact",
    backHome: "Retour à l'accueil",
    results: "résultats",
    filters: "Filtres",
    theme: "Thème",
    ministry: "Ministère",
    sortBy: "Trier par",
    relevance: "Pertinence",
    recent: "Plus récent",
  },
  home: {
    heroEyebrow: "Portail national",
    heroTitle: "Vos démarches, en ligne, en toute confiance.",
    heroText:
      "Accédez à l'ensemble des services publics du Royaume depuis un seul portail : déposez vos demandes, suivez leur avancement et récupérez vos documents officiels, signés électroniquement.",
    searchLabel: "Rechercher une démarche, un service ou une information",
    popularLabel: "Démarches les plus demandées",
    popular: [
      { label: "Extrait d'acte de naissance", href: "/demarches/acte-de-naissance", description: "Obtenir une copie officielle de votre acte de naissance" },
      { label: "Renouvellement de la CNIE", href: "/demarches/renouvellement-cnie", description: "Renouveler votre carte nationale d'identité électronique" },
      { label: "Passeport biométrique", href: "/demarches/passeport-biometrique", description: "Demander ou renouveler votre passeport" },
      { label: "Carte grise", href: "/demarches/carte-grise", description: "Immatriculer ou dupliquer le certificat d'immatriculation de votre véhicule" },
      { label: "Attestation fiscale", href: "/demarches/attestation-fiscale", description: "Télécharger votre attestation de situation fiscale" },
      { label: "Attestation AMO", href: "/demarches/amo", description: "Obtenir votre attestation d'affiliation à l'assurance maladie obligatoire" },
    ],
    themesTitle: "Explorer par thème",
    themesText: "Chaque étape de votre vie administrative, organisée par thème pour trouver rapidement la démarche qui vous concerne.",
    themes: [
      { icon: "FileText", title: "État civil", description: "Naissance, mariage, décès, livret de famille", href: "/demarches?theme=etat-civil", count: 24 },
      { icon: "Fingerprint", title: "Identité & voyage", description: "CNIE, passeport, carte de séjour", href: "/demarches?theme=identite-voyage", count: 18 },
      { icon: "Car", title: "Véhicules & permis", description: "Immatriculation, permis de conduire, contrôle technique", href: "/demarches?theme=vehicules-permis", count: 15 },
      { icon: "Wallet", title: "Impôts & taxes", description: "Déclarations, paiements et attestations fiscales", href: "/demarches?theme=impots-taxes", count: 21 },
      { icon: "Stethoscope", title: "Santé & protection sociale", description: "AMO, CNSS, carnet de santé", href: "/demarches?theme=sante-protection-sociale", count: 19 },
      { icon: "GraduationCap", title: "Éducation", description: "Inscriptions, bourses, équivalences de diplômes", href: "/demarches?theme=education", count: 13 },
      { icon: "Briefcase", title: "Emploi & entreprise", description: "Création d'entreprise, recrutement, formation", href: "/demarches?theme=emploi-entreprise", count: 17 },
      { icon: "Home", title: "Logement & urbanisme", description: "Permis de construire, titres fonciers, aides au logement", href: "/demarches?theme=logement-urbanisme", count: 12 },
    ],
    noticeTitle: "Nouvelle version de l'application mobile",
    noticeText:
      "Suivez l'avancement de vos démarches, recevez des notifications et signez vos documents directement depuis l'application. La mise à jour est disponible sur les deux stores.",
    noticeLink: { label: "Voir la nouveauté", href: "/actualites/nouvelle-version-application-mobile" },
    figuresTitle: "Le portail en chiffres",
    figures: [
      { value: "2,4 M", label: "démarches réalisées ce mois" },
      { value: "540", label: "services en ligne" },
      { value: "1 200", label: "communes connectées" },
      { value: "92 %", label: "taux de satisfaction" },
    ],
    newsTitle: "Actualités",
    news: [
      {
        id: "nouvelle-version-application-mobile",
        date: "15 septembre 2026",
        category: "Service numérique",
        title: "Une nouvelle version de l'application mobile est disponible",
        summary: "L'application du portail national s'enrichit du suivi en temps réel des démarches et de la signature électronique des documents.",
        body: [
          "L'application mobile du portail national des services publics passe à la version 3.0. Disponible dès aujourd'hui sur les stores Android et iOS, cette mise à jour a été conçue à partir des retours de plusieurs milliers d'usagers testeurs.",
          "La nouveauté principale est le suivi en temps réel de l'avancement des démarches : chaque étape, de la réception du dossier à la délivrance du document, est désormais visible directement depuis l'application, avec une notification à chaque changement de statut.",
          "L'application permet également de signer électroniquement certains documents depuis un smartphone, grâce à l'identité numérique nationale. Les usagers disposant déjà d'un compte n'ont aucune démarche supplémentaire à effectuer pour profiter de ces nouveautés.",
        ],
      },
      {
        id: "paiement-en-ligne-taxes-locales",
        date: "2 septembre 2026",
        category: "Fiscalité",
        title: "Le paiement en ligne des taxes locales étendu à 200 communes supplémentaires",
        summary: "Les usagers de 200 nouvelles communes peuvent désormais régler leur taxe d'habitation et leur taxe de services communaux depuis le portail.",
        body: [
          "Après une phase pilote menée dans les grandes villes du Royaume, le paiement en ligne de la taxe d'habitation et de la taxe de services communaux est désormais disponible dans 200 communes supplémentaires, portant à plus de 700 le nombre de communes couvertes.",
          "Les usagers concernés peuvent consulter le montant dû, télécharger leur avis d'imposition et régler leur taxe par carte bancaire, sans se déplacer au guichet. Un reçu numérique est délivré immédiatement après paiement.",
          "Le déploiement se poursuivra au cours des prochains mois, avec pour objectif de couvrir l'ensemble des communes du Royaume d'ici la fin de l'année 2027.",
        ],
      },
      {
        id: "vigilance-sites-frauduleux",
        date: "20 août 2026",
        category: "Sécurité",
        title: "Campagne de vigilance contre les sites frauduleux",
        summary: "Plusieurs signalements de sites imitant le portail national ont été recensés. Un rappel des bons réflexes est publié pour protéger les usagers.",
        body: [
          "Ces dernières semaines, plusieurs sites internet imitant l'apparence du portail national des services publics ont été signalés. Ces sites proposent des démarches payantes qui sont en réalité gratuites, ou tentent de récupérer des données personnelles et bancaires.",
          "Le portail national rappelle que l'ensemble de ses services sont accessibles gratuitement, exclusivement sur des adresses se terminant par gov.ma. Aucune démarche officielle ne demande de paiement par un moyen non sécurisé ou en dehors du portail.",
          "En cas de doute sur l'authenticité d'un site, les usagers sont invités à vérifier l'adresse dans la barre de navigation, à ne jamais communiquer leurs identifiants par e-mail ou téléphone, et à signaler tout site suspect via la rubrique Aide du portail.",
        ],
      },
    ],
    servicesTitle: "Services en ligne à découvrir",
    services: [
      {
        slug: "acte-de-naissance",
        title: "Extrait d'acte de naissance",
        ministry: "Ministère de l'Intérieur",
        theme: "État civil",
        summary: "Demandez et recevez votre acte de naissance signé électroniquement.",
        online: true,
        free: true,
        duration: "48 h",
        popular: true,
      },
      {
        slug: "renouvellement-cnie",
        title: "Renouvellement de la CNIE",
        ministry: "Ministère de l'Intérieur — DGSN",
        theme: "Identité & voyage",
        summary: "Renouvelez votre carte nationale d'identité électronique avant son expiration.",
        online: true,
        free: false,
        duration: "5 jours ouvrés",
        popular: true,
      },
      {
        slug: "passeport-biometrique",
        title: "Passeport biométrique",
        ministry: "Ministère de l'Intérieur — DGSN",
        theme: "Identité & voyage",
        summary: "Prenez rendez-vous et suivez la fabrication de votre passeport.",
        online: true,
        free: false,
        duration: "8 jours ouvrés",
        popular: true,
      },
      {
        slug: "carte-grise",
        title: "Carte grise",
        ministry: "Ministère de l'Équipement et de l'Eau",
        theme: "Véhicules & permis",
        summary: "Immatriculez un véhicule neuf ou demandez un duplicata.",
        online: true,
        free: false,
        duration: "72 h",
        popular: true,
      },
      {
        slug: "attestation-fiscale",
        title: "Attestation fiscale",
        ministry: "Direction Générale des Impôts",
        theme: "Impôts & taxes",
        summary: "Téléchargez votre attestation de régularité fiscale.",
        online: true,
        free: true,
        duration: "Immédiat",
        popular: false,
      },
      {
        slug: "amo",
        title: "Attestation AMO",
        ministry: "Caisse Nationale de Sécurité Sociale (CNSS)",
        theme: "Santé & protection sociale",
        summary: "Téléchargez votre attestation d'affiliation à l'assurance maladie obligatoire.",
        online: true,
        free: true,
        duration: "Immédiat",
        popular: true,
      },
    ],
    identityTitle: "Une seule identité numérique pour tous vos services",
    identityText:
      "Créez votre identité numérique nationale et connectez-vous en toute sécurité à l'ensemble des services publics en ligne, sans avoir à ressaisir vos informations à chaque démarche.",
    identityCta: "Créer mon identité numérique",
    identityPoints: [
      "Une connexion unique et sécurisée à tous les services publics numériques",
      "Vos documents administratifs signés électroniquement, avec la même valeur que l'original",
      "Un suivi centralisé de toutes vos démarches, où que vous soyez",
    ],
    appTitle: "L'administration dans votre poche",
    appText:
      "Suivez vos démarches, recevez vos notifications et téléchargez vos documents officiels depuis l'application mobile du portail national, disponible sur Android et iOS.",
    appCta: "Télécharger l'application",
  },
  procedure: {
    slug: "acte-de-naissance",
    breadcrumb: ["Accueil", "Démarches", "État civil"],
    eyebrow: "Démarche · État civil",
    title: "Demande d'extrait d'acte de naissance",
    ministry: "Ministère de l'Intérieur — Direction Générale des Collectivités Territoriales",
    summary: "Obtenez un extrait de votre acte de naissance signé électroniquement, valable auprès de toutes les administrations.",
    facts: [
      { label: "Délai", value: "48 h" },
      { label: "Coût", value: "Gratuit" },
      { label: "Validité", value: "3 mois" },
      { label: "Public", value: "Toute personne née au Maroc" },
    ],
    tabs: { about: "Présentation", documents: "Documents", steps: "Étapes", faq: "Questions fréquentes" },
    about: [
      "L'extrait d'acte de naissance est un document officiel reprenant les informations essentielles portées sur l'acte de naissance : nom, prénom, date et lieu de naissance, ainsi que la filiation selon le type demandé.",
      "Le document délivré par le portail est signé électroniquement par l'officier d'état civil de la commune de naissance et porte un cachet numérique vérifiable. Il a la même valeur juridique que l'exemplaire délivré au guichet.",
      "La demande peut être faite pour vous-même ou, sous conditions, pour le compte d'un tiers. Le délai moyen de traitement est de 48 heures pour une réception numérique.",
    ],
    eligibility: {
      title: "Qui peut faire cette demande ?",
      items: [
        "Être né(e) sur le territoire marocain et disposer d'un acte de naissance enregistré dans les registres de l'état civil.",
        "Présenter une carte nationale d'identité électronique (CNIE) en cours de validité.",
        "Agir pour le compte d'un tiers uniquement muni d'une procuration légalisée.",
        "Disposer d'un compte sur l'identité numérique nationale pour signer électroniquement la demande.",
      ],
    },
    documents: {
      title: "Documents à préparer",
      items: [
        { label: "Carte nationale d'identité électronique (CNIE)", required: true, hint: "Recto-verso, en cours de validité" },
        { label: "Livret de famille", required: false, hint: "Recommandé pour accélérer la vérification des informations" },
        { label: "Procuration légalisée", required: false, hint: "Obligatoire uniquement si la demande est faite pour le compte d'un tiers" },
        { label: "Justificatif de filiation", required: false, hint: "À joindre si les informations d'état civil ont changé (adoption, reconnaissance, jugement)" },
      ],
    },
    stepsTitle: "Comment ça marche",
    steps: [
      { title: "Identifiez-vous", text: "Connectez-vous avec votre identité numérique nationale ou créez-en une en quelques minutes." },
      { title: "Renseignez la demande", text: "Indiquez la commune de naissance, le type d'extrait souhaité et le nombre d'exemplaires." },
      { title: "Vérifiez et signez", text: "Relisez les informations saisies puis signez électroniquement votre demande." },
      { title: "Recevez votre extrait", text: "Téléchargez votre document signé ou choisissez un retrait en commune ou un envoi postal." },
    ],
    faq: [
      {
        q: "Combien de temps faut-il pour recevoir mon extrait d'acte de naissance ?",
        a: "Le document est généralement délivré sous 48 heures ouvrées pour un envoi numérique. Le retrait en commune ou l'envoi postal peuvent nécessiter un délai supplémentaire.",
      },
      {
        q: "L'extrait d'acte de naissance téléchargé est-il valable comme l'original ?",
        a: "Oui. Le document est signé électroniquement par l'officier d'état civil et porte un cachet numérique vérifiable, avec la même valeur juridique que l'exemplaire papier.",
      },
      {
        q: "Puis-je faire la demande pour un membre de ma famille ?",
        a: "Oui, à condition de joindre une procuration légalisée et une copie de la pièce d'identité de la personne concernée.",
      },
      {
        q: "Que faire si mon acte de naissance comporte une erreur ?",
        a: "Vous devez d'abord effectuer une demande de rectification auprès de la commune ou du tribunal compétent avant de pouvoir obtenir un extrait corrigé.",
      },
    ],
    warning: {
      title: "Attention aux sites frauduleux",
      text: "Ce service est entièrement gratuit et accessible uniquement sur les domaines officiels en gov.ma. Ne communiquez jamais vos identifiants ou vos informations bancaires sur un autre site.",
    },
    form: {
      title: "Nouvelle demande d'extrait d'acte de naissance",
      steps: [
        {
          title: "Identité du demandeur",
          fields: [
            { kind: "text", name: "nom", label: "Nom", required: true },
            { kind: "text", name: "prenom", label: "Prénom", required: true },
            { kind: "text", name: "cnie", label: "Numéro de CNIE", hint: "Format : A123456", required: true, placeholder: "A123456" },
            { kind: "date", name: "dateNaissance", label: "Date de naissance", required: true },
            { kind: "email", name: "email", label: "Adresse e-mail", required: true },
            { kind: "tel", name: "telephone", label: "Téléphone", required: true, addonStart: "+212" },
          ],
        },
        {
          title: "Acte demandé",
          fields: [
            {
              kind: "select",
              name: "communeNaissance",
              label: "Commune de naissance",
              required: true,
              options: [
                { value: "rabat", label: "Rabat" },
                { value: "casablanca", label: "Casablanca" },
                { value: "fes", label: "Fès" },
                { value: "marrakech", label: "Marrakech" },
                { value: "tanger", label: "Tanger" },
                { value: "agadir", label: "Agadir" },
                { value: "sale", label: "Salé" },
                { value: "meknes", label: "Meknès" },
              ],
            },
            {
              kind: "radio",
              name: "typeExtrait",
              label: "Type d'extrait",
              required: true,
              options: [
                { value: "extrait-integral", label: "Extrait intégral", hint: "Reproduit l'ensemble des mentions portées sur l'acte, y compris la filiation" },
                { value: "extrait-simple", label: "Extrait simple", hint: "Reprend uniquement les informations essentielles : nom, prénom, date et lieu de naissance" },
                { value: "copie-integrale", label: "Copie intégrale", hint: "Reproduction exacte de l'acte original avec toutes les mentions marginales" },
              ],
            },
            {
              kind: "select",
              name: "nombreExemplaires",
              label: "Nombre d'exemplaires",
              required: true,
              options: [
                { value: "1", label: "1" },
                { value: "2", label: "2" },
                { value: "3", label: "3" },
                { value: "4", label: "4" },
                { value: "5", label: "5" },
              ],
            },
            {
              kind: "select",
              name: "motif",
              label: "Motif de la demande",
              required: true,
              options: [
                { value: "renouvellement-cnie", label: "Renouvellement de la CNIE" },
                { value: "passeport", label: "Demande de passeport" },
                { value: "mariage", label: "Dossier de mariage" },
                { value: "inscription-scolaire", label: "Inscription scolaire ou universitaire" },
                { value: "autre", label: "Autre motif" },
              ],
            },
            { kind: "checkbox", name: "pourTiers", label: "Cette demande est faite pour le compte d'un tiers" },
            { kind: "file", name: "pieceJointe", label: "Pièce jointe", hint: "Procuration ou justificatif, si nécessaire", accept: ".pdf,.jpg" },
          ],
        },
        {
          title: "Réception",
          fields: [
            {
              kind: "radio",
              name: "modeReception",
              label: "Mode de réception",
              required: true,
              options: [
                { value: "pdf-email", label: "PDF signé par e-mail", hint: "Reçu immédiatement dans votre messagerie une fois le document prêt" },
                { value: "retrait-commune", label: "Retrait en commune", hint: "À récupérer au guichet de votre commune de naissance" },
                { value: "courrier-postal", label: "Envoi par courrier postal", hint: "Délai supplémentaire de 3 à 5 jours ouvrés" },
              ],
            },
            { kind: "text", name: "adresse", label: "Adresse de réception", hint: "Requise uniquement en cas d'envoi postal" },
          ],
        },
      ],
      reviewTitle: "Vérifiez votre demande",
      reviewText: "Relisez attentivement les informations saisies avant de signer et d'envoyer votre demande. Toute erreur peut retarder son traitement.",
      consent: "Je certifie l'exactitude des informations communiquées et j'accepte les conditions générales d'utilisation du service.",
      submit: "Envoyer ma demande",
      previous: "Précédent",
      next: "Suivant",
      saveDraft: "Enregistrer un brouillon",
      draftSavedText: "Conservé sur cet appareil uniquement — démonstration, rien n'est transmis.",
      draftFound: "Un brouillon a été enregistré sur cet appareil.",
      resumeDraft: "Reprendre le brouillon",
      success: {
        title: "Votre demande a bien été envoyée",
        text: "Vous recevrez une notification dès que votre extrait d'acte de naissance sera prêt. Vous pouvez suivre l'avancement de votre demande à tout moment depuis votre espace personnel.",
        reference: "N° 2026-04512",
        nextSteps: [
          "Vous recevrez un e-mail de confirmation avec le numéro de suivi de votre demande.",
          "L'officier d'état civil de votre commune de naissance traite votre demande sous 48 heures.",
          "Vous serez averti(e) par notification dès que le document signé sera disponible au téléchargement.",
        ],
        download: "Télécharger l'accusé de réception",
        track: "Suivre ma demande",
      },
    },
  },
  ministry: {
    breadcrumb: ["Accueil", "Institutions", "Ministère de la Transition Numérique et de la Réforme de l'Administration"],
    name: "Ministère de la Transition Numérique et de la Réforme de l'Administration",
    short: "MTNRA",
    mission:
      "Le Ministère de la Transition Numérique et de la Réforme de l'Administration pilote la stratégie de digitalisation des services publics marocains. Il coordonne la simplification des procédures administratives, l'interopérabilité des systèmes d'information de l'État et le développement de l'identité numérique nationale.",
    missionsTitle: "Nos missions",
    missions: [
      {
        title: "Simplifier les démarches administratives",
        text: "Réduire les délais et le nombre de pièces justificatives exigées pour chaque procédure, en s'appuyant sur l'échange de données entre administrations.",
      },
      {
        title: "Généraliser les services en ligne",
        text: "Rendre accessibles sur le portail national l'ensemble des démarches à fort volume, avec un même niveau de qualité de service partout au Royaume.",
      },
      {
        title: "Déployer l'identité numérique",
        text: "Permettre à chaque citoyen de s'authentifier une seule fois pour accéder à tous les services publics numériques.",
      },
      {
        title: "Ouvrir les données publiques",
        text: "Favoriser la transparence et l'innovation en publiant les données non sensibles produites par les administrations.",
      },
    ],
    servicesTitle: "Services en ligne du ministère",
    services: [
      { label: "Portail national des services publics", href: "/", description: "Toutes les démarches administratives en un seul endroit" },
      { label: "Idarati.ma", href: "https://www.idarati.ma", description: "Annuaire des procédures et documents administratifs" },
      { label: "Chikaya.ma", href: "https://www.chikaya.ma", description: "Déposer une réclamation auprès d'une administration" },
      { label: "Données ouvertes", href: "https://data.gov.ma", description: "Jeux de données publics réutilisables" },
      { label: "Identité numérique nationale", href: "/aide", description: "Créer et gérer votre identité numérique" },
      { label: "Signature électronique", href: "/aide", description: "Signer vos documents administratifs en ligne" },
    ],
    figures: [
      { value: "540", label: "services en ligne disponibles" },
      { value: "1 200", label: "communes raccordées au portail" },
      { value: "3,2 M", label: "identités numériques activées" },
      { value: "98 %", label: "disponibilité de la plateforme" },
    ],
    newsTitle: "Actualités du ministère",
    organisationTitle: "Organisation",
    organisation: [
      {
        title: "Agence de Développement du Digital (ADD)",
        text: "Met en œuvre la stratégie nationale de transformation numérique et accompagne les administrations dans leurs projets de digitalisation.",
      },
      {
        title: "Direction de la Réforme de l'Administration",
        text: "Pilote la simplification des procédures administratives et l'amélioration de la relation entre l'administration et les usagers.",
      },
      {
        title: "Direction des Systèmes d'Information de l'État",
        text: "Assure l'interopérabilité des systèmes d'information et la sécurité des plateformes numériques publiques.",
      },
      {
        title: "Institut Supérieur de l'Administration",
        text: "Forme les cadres de la fonction publique aux métiers du numérique et de la gestion administrative moderne.",
      },
    ],
    contactTitle: "Nous contacter",
    contact: {
      address: "Avenue Annakhil, Hay Riad, Rabat",
      phone: "+212 5 37 68 00 00",
      email: "contact@mtnra.gov.ma",
      hours: "Lundi – vendredi, 8 h 30 – 16 h 30",
    },
    documentsTitle: "Publications",
    documents: [
      { title: "Rapport annuel de la transformation numérique 2025", format: "PDF", size: "4,2 Mo", date: "12 mars 2026" },
      { title: "Stratégie nationale Maroc Digital 2030", format: "PDF", size: "2,8 Mo", date: "5 février 2026" },
      { title: "Guide d'utilisation du portail national", format: "PDF", size: "1,1 Mo", date: "18 janvier 2026" },
      { title: "Baromètre de la satisfaction des usagers 2025", format: "PDF", size: "980 Ko", date: "30 avril 2026" },
    ],
  },
  search: {
    title: "Résultats de recherche",
    query: "acte de naissance",
    resultsCount: "{count} résultats pour « {query} »",
    filterThemes: ["État civil", "Identité & voyage", "Santé & protection sociale", "Éducation", "Emploi & entreprise"],
    filterMinistries: [
      "Ministère de l'Intérieur",
      "Ministère de la Santé et de la Protection Sociale",
      "Ministère des Affaires Étrangères, de la Coopération Africaine et des Marocains Résidant à l'Étranger",
      "Ministère de la Transition Numérique et de la Réforme de l'Administration",
    ],
    results: [
      {
        title: "Demande d'extrait d'acte de naissance",
        href: "/demarches/acte-de-naissance",
        ministry: "Ministère de l'Intérieur",
        summary: "Obtenez un extrait de votre acte de naissance signé électroniquement, valable auprès de toutes les administrations.",
        online: true,
        updated: "10 septembre 2026",
      },
      {
        title: "Rectification d'un acte de naissance",
        href: "/demarches/rectification-acte-naissance",
        ministry: "Ministère de l'Intérieur",
        summary: "Corrigez une erreur ou une omission constatée sur un acte de naissance.",
        online: false,
        updated: "3 septembre 2026",
      },
      {
        title: "Acte de naissance pour Marocains résidant à l'étranger",
        href: "/demarches/acte-naissance-mre",
        ministry: "Ministère des Affaires Étrangères, de la Coopération Africaine et des Marocains Résidant à l'Étranger",
        summary: "Demandez un extrait d'acte de naissance depuis votre consulat ou en ligne.",
        online: true,
        updated: "28 août 2026",
      },
      {
        title: "Légalisation de documents d'état civil",
        href: "/demarches/legalisation-document",
        ministry: "Ministère de l'Intérieur",
        summary: "Faites légaliser vos documents d'état civil pour une utilisation à l'étranger.",
        online: false,
        updated: "15 juillet 2026",
      },
      {
        title: "Déclaration de naissance d'un enfant",
        href: "/demarches/declaration-naissance",
        ministry: "Ministère de la Santé et de la Protection Sociale",
        summary: "Déclarez la naissance de votre enfant auprès de la commune dans les délais légaux.",
        online: false,
        updated: "5 juin 2026",
      },
      {
        title: "Guide : comment obtenir un acte de naissance",
        href: "/aide/guide-acte-de-naissance",
        ministry: "Ministère de la Transition Numérique et de la Réforme de l'Administration",
        summary: "Toutes les étapes expliquées simplement pour obtenir votre acte de naissance en ligne.",
        online: true,
        updated: "1 septembre 2026",
      },
    ],
    noResults: "Aucun résultat ne correspond à votre recherche. Essayez avec d'autres mots-clés ou consultez nos suggestions ci-dessous.",
    suggestions: ["copie intégrale d'acte de naissance", "rectification acte de naissance", "acte de naissance Marocains à l'étranger"],
  },
  news: {
    title: "Actualités",
    intro: "Toute l'actualité des services publics et des démarches en ligne.",
    categories: ["Service numérique", "Fiscalité", "Sécurité", "Simplification"],
  },
  errors: {
    demoStubTitle: "Page non réalisée dans cette démonstration",
    demoStubText: "Ce lien existe pour rendre la navigation réaliste, mais la page n'a pas été construite. Les composants nécessaires sont disponibles dans la documentation DSM.",
    notFoundTitle: "Page introuvable",
    notFoundText: "La page que vous recherchez n'existe pas ou a été déplacée. Vérifiez l'adresse ou utilisez la recherche.",
    serverTitle: "Une erreur est survenue",
    serverText: "Le service rencontre un problème technique. Veuillez réessayer dans quelques instants.",
    maintenanceTitle: "Service temporairement indisponible",
    maintenanceText: "Cette page est en maintenance. Le service sera rétabli sous peu, merci de votre patience.",
    suggestionsTitle: "Vous cherchiez peut-être",
    suggestions: [
      { label: "Accueil", href: "/" },
      { label: "Démarches", href: "/demarches" },
      { label: "Aide", href: "/aide" },
      { label: "Actualités", href: "/actualites" },
    ],
  },
  footer: {
    description:
      "Le portail national des services publics du Royaume du Maroc regroupe les démarches administratives et les informations officielles de l'ensemble des ministères et institutions publiques.",
    ecosystem: [
      { label: "maroc.ma", href: "https://www.maroc.ma" },
      { label: "Idarati.ma", href: "https://www.idarati.ma" },
      { label: "Chikaya.ma", href: "https://www.chikaya.ma" },
      { label: "Service-public.ma", href: "https://www.service-public.ma" },
    ],
    columns: [
      {
        title: "Démarches",
        links: [
          { label: "État civil", href: "/demarches?theme=etat-civil" },
          { label: "Identité & voyage", href: "/demarches?theme=identite-voyage" },
          { label: "Véhicules & permis", href: "/demarches?theme=vehicules-permis" },
          { label: "Impôts & taxes", href: "/demarches?theme=impots-taxes" },
        ],
      },
      {
        title: "Institutions",
        links: [
          { label: "Ministère de la Transition Numérique et de la Réforme de l'Administration", href: "/institutions/ministere" },
          { label: "Actualités", href: "/actualites" },
          { label: "Aide", href: "/aide" },
          { label: "Recherche", href: "/recherche" },
        ],
      },
      {
        title: "Ressources",
        links: [
          { label: "Guide des démarches en ligne", href: "/aide" },
          { label: "Application mobile", href: "/aide/application-mobile" },
          { label: "Données ouvertes", href: "https://data.gov.ma" },
          { label: "Statistiques du portail", href: "/actualites/statistiques-portail" },
        ],
      },
    ],
    bottomLinks: [
      { label: "Plan du site", href: "/plan-du-site" },
      { label: "Accessibilité : partiellement conforme", href: "/accessibilite" },
      { label: "Mentions légales", href: "/mentions-legales" },
      { label: "Données personnelles", href: "/donnees-personnelles" },
      { label: "Gestion des cookies", href: "/cookies" },
    ],
    license: "Sauf mention contraire, les informations publiées sur ce site sont libres de réutilisation, sous réserve de la mention de leur source.",
    newsletterTitle: "Restez informé",
    newsletterText: "Recevez l'actualité des services publics et les nouveautés du portail directement par e-mail.",
  },
};

export default content;
