// Tamazight (IRCAM standard) — à faire relire par un locuteur natif
import type { DemoContent } from "./types";

const content: DemoContent = {
  meta: {
    siteTitle: "ⵜⴰⴱⴱⵓⵔⵜ ⵜⴰⵏⴰⵎⵓⵔⵜ ⵏ ⵜⵏⴰⴼⵓⵜⵉⵏ ⵜⵉⴳⴷⵓⴷⴰⵏⵉⵏ",
    tagline: "ⵜⵉⵎⵢⵓⵔⵉⵏ ⵏⵏⵓⵏ, ⵙ ⵜⵓⵙⴷⵉⴷⵜ.",
    entity: "ⵜⴰⵎⴰⵡⴰⵙⵜ ⵏ ⵓⵙⵎⵓⵜⵜⵉ ⴰⵎⵙⵙⵏⴳⴰⵍ ⴷ ⵓⵚⵍⵍⴰⵃ ⵏ ⵜⵏⴱⴰⴹⵜ",
    description:
      "ⵜⴰⴱⴱⵓⵔⵜ ⵜⴰⵏⵚⵉⴱⵜ ⵏ ⵜⵎⵢⵓⵔⵉⵏ ⴷ ⵜⵏⴰⴼⵓⵜⵉⵏ ⵜⵉⴳⴷⵓⴷⴰⵏⵉⵏ ⵏ ⵜⴳⵍⴷⵉⵜ ⵏ ⵍⵎⵖⵔⵉⴱ: ⵜⵓⴷⵔⵜ ⵜⴰⴳⴷⵓⴷⴰⵏⵜ, ⴰⵎⴰⴳⵏⵓ, ⵜⵓⴽⴰⵔⵉⵏ, ⵜⵉⵙⵎⴹⴰⵍ, ⵜⴰⴷⵓⵙⵉ, ⴰⵙⴳⵎⵉ, ⴰⵛⵖⴰⵍ ⴷ ⴰⵏⵣⴳⵓⵎ.",
    officialBanner: "ⴰⵙⵉⵜ ⵓⵏⵚⵉⴱ ⵏ ⵜⴳⵍⴷⵉⵜ ⵏ ⵍⵎⵖⵔⵉⴱ",
    demoNotice: "ⴰⵙⴽⴰⵏ ⴰⵎⵙⵉⵎⴰⵏ: ⵜⴰⴱⴱⵓⵔⵜ ⴰⴷ ⵜⴰⵎⵙⴽⴰⵔⵜ ⵜⵙⴽⴰⵏ ⴰⵏⴰⴳⵔⴰⵡ ⵏ ⵓⵙⴳⴳⴰ DSM. ⵓⵔ ⵉⴳⵉ ⴰⵙⵉⵜ ⵓⵏⵚⵉⴱ, ⵓⵔ ⵜⵜⵓⵣⵏⴻⵏ ⵉⵙⴼⴽⴰ.",
    demoNoticeLink: "ⵙⵙⵏ DSM",
  },
  nav: [
    { label: "ⵜⴰⵙⵏⴰ ⵜⴰⵎⵣⵡⴰⵔⵓⵜ", href: "/" },
    {
      label: "ⵜⵉⵎⵢⵓⵔⵉⵏ",
      href: "/demarches",
      children: [
        { label: "ⵜⵓⴷⵔⵜ ⵜⴰⴳⴷⵓⴷⴰⵏⵜ", href: "/demarches?theme=etat-civil", description: "ⵜⵉⵍⴰⵍⵉⵜ, ⵣⵡⴰⵊ, ⵜⴰⵎⵜⵜⴰⵏⵜ, ⴰⴽⵜⴰⴱ ⵏ ⵜⵡⵊⴰ" },
        { label: "ⴰⵎⴰⴳⵏⵓ ⴷ ⵓⵜⵜⵓⵔ", href: "/demarches?theme=identite-voyage", description: "ⵜⴰⴽⴰⵕⴹⴰ ⵜⴰⵏⴰⵎⵓⵔⵜ, ⴰⵙⴰⵢⵙ ⵏ ⵓⵜⵜⵓⵔ, ⵜⴰⴽⴰⵕⴹⴰ ⵏ ⵜⵎⴰⵣⵉⵔⵜ" },
        { label: "ⵜⵓⴽⴰⵔⵉⵏ ⴷ ⵉⵙⴰⵢⵙⵏ ⵏ ⵓⵙⵉⵜⵜⵍ", href: "/demarches?theme=vehicules-permis", description: "ⴰⵙⵎⴹⵏ, ⴰⵙⴰⵢⵙ ⵏ ⵓⵙⵉⵜⵜⵍ, ⴰⵙⵥⵕⴰⵢ ⴰⵜⵉⴽⵏⵉⴽ" },
        { label: "ⵜⵉⵙⵎⴹⴰⵍ", href: "/demarches?theme=impots-taxes", description: "ⵜⵉⵎⵍⵖⴰⵢⵉⵏ, ⵜⵉⵅⵍⴰⵚⵉⵏ ⴷ ⵜⵎⴰⴳⵉⵜ ⵏ ⵜⵙⵎⴹⴰⵍ" },
        { label: "ⵜⴰⴷⵓⵙⵉ ⴷ ⵜⵃⵉⵎⴰⵢⵜ ⵜⴰⵏⴰⵎⵓⵏⵜ", href: "/demarches?theme=sante-protection-sociale", description: "AMO, CNSS, ⴰⴽⵜⴰⴱ ⴰⴷⵓⵙⴰⵏ" },
        { label: "ⴰⵙⴳⵎⵉ", href: "/demarches?theme=education", description: "ⵉⵙⵎⵜⴰⵢⵏ, ⵜⵉⵎⵓⵜⵜⵉ, ⴰⵙⵙⵎⵢⴰⵡⴰⴹ ⵏ ⵜⵖⴹⴼⵉⵏ" },
        { label: "ⴰⵛⵖⴰⵍ ⴷ ⵜⴰⵎⵙⵎⵓⵏⵜ", href: "/demarches?theme=emploi-entreprise", description: "ⴰⵙⵏⵓⵍⴼⵓ ⵏ ⵜⵎⵙⵎⵓⵏⵉⵏ, ⴰⵙⵙⵉⴷⴼ ⴷ ⵓⵙⵎⵓⵜⵜⴳ" },
        { label: "ⴰⵏⵣⴳⵓⵎ ⴷ ⵓⵙⵉⴳⴳⵣ", href: "/demarches?theme=logement-urbanisme", description: "ⴰⵙⴰⵢⵙ ⵏ ⵓⴱⵏⵏⴰ, ⵉⵎⵓⵔⴰ ⵏ ⵜⵎⵓⵔⵜ, ⵜⴰⵎⵓⴹⴰⵏⵜ ⵏ ⵓⵏⵣⴳⵓⵎ" },
      ],
      featured: {
        title: "ⵜⴰⵏⴼⴰⵙⵜ ⵏ ⵜⵍⴰⵍⵉⵜ ⴳ ⵜⵉⵏⵜⵉⵔⵏⵉⵜ",
        text: "ⴰⵡⵉⵜ ⵜⴰⵏⴼⴰⵙⵜ ⵏ ⵜⵍⴰⵍⵉⵜ ⵏⵏⵓⵏ ⵉⵜⵜⵓⵥⵕⵥⵎⵏ ⵙ ⵓⵣⴹⴰⵢ ⴰⵏⴳⵔⴰⵡ, ⴱⵍⴰ ⴰⴷ ⵜⵜⵓⵔⵎ.",
        href: "/demarches/acte-de-naissance",
        cta: "ⵙⴽⵔ ⵜⴰⵏⵎⵔⵜ ⵉⵏⵓ",
      },
    },
    { label: "ⵜⵉⵖⵔⵎⵉⵡⵉⵏ", href: "/institutions/ministere" },
    { label: "ⵉⵏⵖⵎⵉⵙⵏ", href: "/actualites" },
    { label: "ⵜⴰⵡⵉⵙⵉ", href: "/aide" },
  ],
  common: {
    home: "ⵜⴰⵙⵏⴰ ⵜⴰⵎⵣⵡⴰⵔⵓⵜ",
    allServices: "ⴽⵓⵍⵍⵓ ⵜⵉⵏⴰⴼⵓⵜⵉⵏ",
    seeAll: "ⵥⵕ ⴽⵓⵍⵍⵓ",
    readMore: "ⵖⵔ ⵓⴳⴳⴰⵔ",
    startProcedure: "ⴱⴷⵓ ⵜⴰⵎⵢⵓⵔⵜ",
    online: "ⴳ ⵜⵉⵏⵜⵉⵔⵏⵉⵜ",
    free: "ⴱⴰⵛⵉ ⵙ ⵢⴰⵏ",
    paid: "ⵉⵜⵜⵓⵅⵍⵍⵚ",
    duration: "ⴰⴽⵓⴷ",
    updatedOn: "ⵉⵜⵜⵓⵙⵎⴰⵢⵏⵓ ⴰⵙⵙ ⵏ",
    share: "ⴱⴹⵓ",
    print: "ⵙⵉⵖⵍ",
    helpTitle: "ⵉⵜⵜⵡⴰⵙⵔⴰ ⵜⴰⵡⵉⵙⵉ?",
    helpText: "ⵉⵎⵛⴰⵡⴰⵕⵏ ⵏⵏⵖ ⴰⴷ ⴰⵡⵏ ⴰⵡⵙⵏ ⴳ ⵜⵎⵢⵓⵔⵉⵏ ⵏⵏⵓⵏ.",
    helpCta: "ⵏⵎⵎⴰⵖⴰⵜ ⴷ ⵜⵡⵉⵙⵉ",
    contact: "ⴰⵎⵢⴰⵡⴰⴹ",
    backHome: "ⴰⵖⵓⵍ ⵖⵔ ⵜⴰⵙⵏⴰ ⵜⴰⵎⵣⵡⴰⵔⵓⵜ",
    results: "ⵉⵎⵢⴰⵡⴰⴹⵏ",
    filters: "ⵉⵙⵜⴰⵢⵏ",
    theme: "ⴰⵙⵓⴳⵣ",
    ministry: "ⵜⴰⵎⴰⵡⴰⵙⵜ",
    sortBy: "ⵙⵎⵢⵓⵔ ⵙ",
    relevance: "ⴰⵎⵣⵡⴰⵔⵓ",
    recent: "ⴰⵎⴰⵢⵏⵓ",
  },
  home: {
    heroEyebrow: "ⵜⴰⴱⴱⵓⵔⵜ ⵜⴰⵏⴰⵎⵓⵔⵜ",
    heroTitle: "ⵜⵉⵎⵢⵓⵔⵉⵏ ⵏⵏⵓⵏ, ⴳ ⵜⵉⵏⵜⵉⵔⵏⵉⵜ, ⵙ ⵜⵍⴰⵖⵜ.",
    heroText:
      "ⴽⵛⵎⵜ ⵖⵔ ⴽⵓⵍⵍⵓ ⵜⵏⴰⴼⵓⵜⵉⵏ ⵜⵉⴳⴷⵓⴷⴰⵏⵉⵏ ⵏ ⵜⴳⵍⴷⵉⵜ ⵙⴳ ⵢⴰⵜ ⵜⴰⴱⴱⵓⵔⵜ: ⵙⵙⵉⴼⴹⵜ ⵜⵉⵏⵎⵔⵉⵏ ⵏⵏⵓⵏ, ⴹⴼⵕⵜ ⴰⵎⵢⵓⵔ ⵏⵏⵙⵏⵜ ⴷ ⴰⵡⵉⵜ ⵉⵙⴰⴹⵓⴼⵏ ⵏⵏⵓⵏ ⵉⵜⵜⵓⵥⵕⵥⵎⵏ.",
    searchLabel: "ⵔⵣⵓ ⵅⴼ ⵜⴰⵎⵢⵓⵔⵜ, ⵜⴰⵏⴰⴼⵓⵜ ⵏⵖ ⵜⴰⵍⵖⴰ",
    popularLabel: "ⵜⵉⵎⵢⵓⵔⵉⵏ ⵉⵜⵜⵡⴰⵔⵉⵏ ⵓⴳⴳⴰⵔ",
    popular: [
      { label: "ⵜⴰⵏⴼⴰⵙⵜ ⵏ ⵜⵍⴰⵍⵉⵜ", href: "/demarches/acte-de-naissance", description: "ⴰⵡⵉ ⵢⴰⵜ ⵜⵏⴼⴰⵙⵜ ⵜⴰⵏⵚⵉⴱⵜ ⵏ ⵜⵍⴰⵍⵉⵜ ⵏⵏⴽ" },
      { label: "ⴰⵙⵎⴰⵢⵏⵓ ⵏ ⵜⴽⴰⵕⴹⴰ ⵜⴰⵏⴰⵎⵓⵔⵜ", href: "/demarches/renouvellement-cnie", description: "ⵙⵎⴰⵢⵏⵓ ⵜⴰⴽⴰⵕⴹⴰ ⵏⵏⴽ ⵜⴰⵏⴰⵎⵓⵔⵜ" },
      { label: "ⴰⵙⴰⵢⵙ ⵏ ⵓⵜⵜⵓⵔ ⴰⴱⵢⵓⵎⵉⵜⵔⵉ", href: "/demarches/passeport-biometrique", description: "ⵙⵓⵜⵔ ⵏⵖ ⵙⵎⴰⵢⵏⵓ ⴰⵙⴰⵢⵙ ⵏ ⵓⵜⵜⵓⵔ ⵏⵏⴽ" },
      { label: "ⵜⴰⴽⴰⵕⴹⴰ ⵜⴰⵎⵣⵉⵢⴰⵏⵜ", href: "/demarches/carte-grise", description: "ⵙⵎⴹ ⵜⴰⴽⴰⵔⵜ ⵜⴰⵎⴰⵢⵏⵓⵜ ⵏⵖ ⵙⵓⵜⵔ ⵢⴰⵜ ⵜⴰⵏⵜⴰⵍⴰ" },
      { label: "ⵜⴰⵎⴰⴳⵉⵜ ⵏ ⵜⵙⵎⴹⵍⵜ", href: "/demarches/attestation-fiscale", description: "ⴰⵣⴷⵎ ⵜⴰⵎⴰⴳⵉⵜ ⵏ ⵓⵣⴰⴷⵖ ⵏⵏⴽ ⴰⵙⵎⴹⴰⵏ" },
      { label: "ⵜⴰⵎⴰⴳⵉⵜ AMO", href: "/demarches/amo", description: "ⴰⵡⵉ ⵜⴰⵎⴰⴳⵉⵜ ⵏ ⵓⵙⵙⵉⴷⴼ ⵏⵏⴽ ⴳ ⵓⵙⵙⴳⵎⵙ ⵉⵜⵜⵡⴰⵜⵜⵔⵏ ⵅⴼ ⵜⵓⴹⵏⵜ" },
    ],
    themesTitle: "ⵔⵣⵓ ⵙ ⵓⵙⵓⴳⵣ",
    themesText: "ⴽⵓⵍⵍⵓ ⵜⴰⵙⵓⵔⵉⴼⵜ ⵏ ⵜⵓⴷⵔⵜ ⵏⵏⵓⵏ ⵜⴰⵏⴱⴰⴹⴰⵏⵜ, ⵜⵓⵙⴳⵎⵓ ⵙ ⵓⵙⵓⴳⵣ ⵃⵎⴰ ⴰⴷ ⵜⴰⴼⵎ ⴷⵖⵢⴰ ⵜⴰⵎⵢⵓⵔⵜ ⵉⵅⵚⵚⵏ.",
    themes: [
      { icon: "FileText", title: "ⵜⵓⴷⵔⵜ ⵜⴰⴳⴷⵓⴷⴰⵏⵜ", description: "ⵜⵉⵍⴰⵍⵉⵜ, ⵣⵡⴰⵊ, ⵜⴰⵎⵜⵜⴰⵏⵜ, ⴰⴽⵜⴰⴱ ⵏ ⵜⵡⵊⴰ", href: "/demarches?theme=etat-civil", count: 24 },
      { icon: "Fingerprint", title: "ⴰⵎⴰⴳⵏⵓ ⴷ ⵓⵜⵜⵓⵔ", description: "ⵜⴰⴽⴰⵕⴹⴰ ⵜⴰⵏⴰⵎⵓⵔⵜ, ⴰⵙⴰⵢⵙ ⵏ ⵓⵜⵜⵓⵔ, ⵜⴰⴽⴰⵕⴹⴰ ⵏ ⵜⵎⴰⵣⵉⵔⵜ", href: "/demarches?theme=identite-voyage", count: 18 },
      { icon: "Car", title: "ⵜⵓⴽⴰⵔⵉⵏ ⴷ ⵉⵙⴰⵢⵙⵏ ⵏ ⵓⵙⵉⵜⵜⵍ", description: "ⴰⵙⵎⴹⵏ, ⴰⵙⴰⵢⵙ ⵏ ⵓⵙⵉⵜⵜⵍ, ⴰⵙⵥⵕⴰⵢ ⴰⵜⵉⴽⵏⵉⴽ", href: "/demarches?theme=vehicules-permis", count: 15 },
      { icon: "Wallet", title: "ⵜⵉⵙⵎⴹⴰⵍ", description: "ⵜⵉⵎⵍⵖⴰⵢⵉⵏ, ⵜⵉⵅⵍⴰⵚⵉⵏ ⴷ ⵜⵎⴰⴳⵉⵜ ⵏ ⵜⵙⵎⴹⴰⵍ", href: "/demarches?theme=impots-taxes", count: 21 },
      { icon: "Stethoscope", title: "ⵜⴰⴷⵓⵙⵉ ⴷ ⵜⵃⵉⵎⴰⵢⵜ ⵜⴰⵏⴰⵎⵓⵏⵜ", description: "AMO, CNSS, ⴰⴽⵜⴰⴱ ⴰⴷⵓⵙⴰⵏ", href: "/demarches?theme=sante-protection-sociale", count: 19 },
      { icon: "GraduationCap", title: "ⴰⵙⴳⵎⵉ", description: "ⵉⵙⵎⵜⴰⵢⵏ, ⵜⵉⵎⵓⵜⵜⵉ, ⴰⵙⵙⵎⵢⴰⵡⴰⴹ ⵏ ⵜⵖⴹⴼⵉⵏ", href: "/demarches?theme=education", count: 13 },
      { icon: "Briefcase", title: "ⴰⵛⵖⴰⵍ ⴷ ⵜⴰⵎⵙⵎⵓⵏⵜ", description: "ⴰⵙⵏⵓⵍⴼⵓ ⵏ ⵜⵎⵙⵎⵓⵏⵉⵏ, ⴰⵙⵙⵉⴷⴼ ⴷ ⵓⵙⵎⵓⵜⵜⴳ", href: "/demarches?theme=emploi-entreprise", count: 17 },
      { icon: "Home", title: "ⴰⵏⵣⴳⵓⵎ ⴷ ⵓⵙⵉⴳⴳⵣ", description: "ⴰⵙⴰⵢⵙ ⵏ ⵓⴱⵏⵏⴰ, ⵉⵎⵓⵔⴰ ⵏ ⵜⵎⵓⵔⵜ, ⵜⴰⵎⵓⴹⴰⵏⵜ ⵏ ⵓⵏⵣⴳⵓⵎ", href: "/demarches?theme=logement-urbanisme", count: 12 },
    ],
    noticeTitle: "ⵜⴰⵍⵖⴰ ⵜⴰⵎⴰⵢⵏⵓⵜ ⵏ ⵓⵙⵏⴼⴰⵔ ⴰⵏⴰⵎⴱⴰⵢⵍ",
    noticeText:
      "ⴹⴼⵕ ⴰⵎⵢⵓⵔ ⵏ ⵜⵎⵢⵓⵔⵉⵏ ⵏⵏⵓⵏ, ⴰⵡⵉ ⵉⵏⵖⵎⵉⵙⵏ ⴷ ⵥⵕⵥⵎ ⵉⵙⴰⴹⵓⴼⵏ ⵏⵏⵓⵏ ⵙⴳ ⵓⵙⵏⴼⴰⵔ ⵙ ⵓⵏⵎⴰⵍⴰ. ⴰⵙⵎⴰⵢⵏⵓ ⵢⵍⵍⴰ ⴳ ⵙⵉⵏ ⵜⵃⴰⵏⵓⵜⵉⵏ.",
    noticeLink: { label: "ⵥⵕ ⴰⵎⴰⵢⵏⵓ", href: "/actualites/nouvelle-version-application-mobile" },
    figuresTitle: "ⵜⴰⴱⴱⵓⵔⵜ ⵙ ⵉⵎⵙⵙⴽⴰⵏⵏ",
    figures: [
      { value: "2,4 ⵎ", label: "ⵜⵉⵎⵢⵓⵔⵉⵏ ⵜⵜⵓⴳⴰⵏⵉⵏ ⴰⵢⵢⵓⵔ ⴰ" },
      { value: "540", label: "ⵜⵉⵏⴰⴼⵓⵜⵉⵏ ⴳ ⵜⵉⵏⵜⵉⵔⵏⵉⵜ" },
      { value: "1200", label: "ⵜⵉⵖⵔⵎⵉⵡⵉⵏ ⵣⴷⵉⵏⵜ ⴷ ⵜⴱⴱⵓⵔⵜ" },
      { value: "92%", label: "ⴰⵣⴷⴰⵢ ⵏ ⵓⵎⵓⵔⵙ" },
    ],
    newsTitle: "ⵉⵏⵖⵎⵉⵙⵏ",
    news: [
      {
        id: "nouvelle-version-application-mobile",
        date: "15/09/2026",
        category: "ⵜⴰⵏⴰⴼⵓⵜ ⵜⴰⵏⴳⵔⴰⵡⴰⵏⵜ",
        title: "ⵜⴰⵍⵖⴰ ⵜⴰⵎⴰⵢⵏⵓⵜ ⵏ ⵓⵙⵏⴼⴰⵔ ⴰⵏⴰⵎⴱⴰⵢⵍ ⵜⵍⵍⴰ ⴷⵖⵉ",
        summary: "ⴰⵙⵏⴼⴰⵔ ⵏ ⵜⴱⴱⵓⵔⵜ ⵜⴰⵏⴰⵎⵓⵔⵜ ⵢⵓⵎⵥ ⴰⴹⴼⴰⵕ ⵏ ⵜⵎⵢⵓⵔⵉⵏ ⵙ ⵜⵓⵔⴰ ⴷ ⵓⵥⵕⵥⵓⵎ ⴰⵏⴳⵔⴰⵡ ⵏ ⵉⵙⴰⴹⵓⴼⵏ.",
        body: [
          "ⴰⵙⵏⴼⴰⵔ ⴰⵏⴰⵎⴱⴰⵢⵍ ⵏ ⵜⴱⴱⵓⵔⵜ ⵜⴰⵏⴰⵎⵓⵔⵜ ⵏ ⵜⵏⴰⴼⵓⵜⵉⵏ ⵜⵉⴳⴷⵓⴷⴰⵏⵉⵏ ⵢⵓⵛⴽⴰ ⵖⵔ ⵜⴰⵍⵖⴰ 3.0. ⵢⵍⵍⴰ ⴷⵖⵉ ⴳ ⵙⵉⵏ ⵜⵃⴰⵏⵓⵜⵉⵏ, ⵢⵓⵙⴽⴰⵔ ⵙ ⵜⵎⵍⵉⵍⵜ ⴷ ⴰⴳⴰⴷⴰⵣ ⵏ ⵉⵎⵙⵙⵎⵔⴰⵙⵏ.",
          "ⵜⴰⵍⵖⴰ ⵜⴰⵎⵣⵡⴰⵔⵓⵜ ⴷ ⴰⴹⴼⴰⵕ ⵏ ⵜⵎⵢⵓⵔⵉⵏ ⵙ ⵜⵓⵔⴰ: ⵜⴰⵙⵓⵔⵉⴼⵜ ⴽⵓⵍⵍⵓ, ⵙⴳ ⵓⵙⵉⵜⵉ ⵏ ⵓⵎⵢⴰⵡⴰⴹ ⴰⵔ ⵜⵓⵣⵏⵜ ⵏ ⵓⵙⴰⴹⵓⴼ, ⵜⵣⵎⵔ ⴰⴷ ⵜⵜⵓⵥⵕ ⵙⴳ ⵓⵙⵏⴼⴰⵔ, ⴷ ⵢⴰⵏ ⵓⵏⵖⵎⵉⵙ ⴳ ⵢⴰⵍ ⴰⵙⵏⴼⵍ.",
          "ⴰⵙⵏⴼⴰⵔ ⵉⵣⵎⵔ ⴰⴷ ⵢⵥⵕⵥⵎ ⴽⵔⴰ ⵏ ⵉⵙⴰⴹⵓⴼⵏ ⵙⴳ ⵓⵜⵉⵍⵉⴼⵓⵏ, ⵙ ⵜⵎⴰⴳⵉⵜ ⵜⴰⵏⴳⵔⴰⵡⴰⵏⵜ ⵜⴰⵏⴰⵎⵓⵔⵜ. ⵉⵎⵙⵙⵎⵔⴰⵙⵏ ⵢⵍⵍⴰⵏ ⴷⴰⵖ ⴷ ⴰⵎⵉⴹⴰⵏ ⵓⵔ ⵅⵚⵚⴰⵏ ⵛⵔⴰ.",
        ],
      },
      {
        id: "paiement-en-ligne-taxes-locales",
        date: "02/09/2026",
        category: "ⵜⵉⵙⵎⴹⴰⵍ",
        title: "ⵜⴰⵅⵍⴰⵚⵜ ⴳ ⵜⵉⵏⵜⵉⵔⵏⵉⵜ ⵏ ⵜⵙⵎⴹⴰⵍ ⵜⵉⵖⵔⵎⵉⵢⵉⵏ ⵜⵓⵙⵎⴰⴹ ⵖⵔ 200 ⵏ ⵜⵖⵔⵎⵉⵡⵉⵏ ⵜⵉⵎⴰⵢⵏⵓⵜⵉⵏ",
        summary: "ⵉⵎⵙⵙⵎⵔⴰⵙⵏ ⵏ 200 ⵏ ⵜⵖⵔⵎⵉⵡⵉⵏ ⵜⵉⵎⴰⵢⵏⵓⵜⵉⵏ ⵣⵎⵔⵏ ⴰⴷ ⵅⵍⵚⵏ ⵜⴰⵙⵎⴹⵍⵜ ⵏ ⵜⵎⵣⴷⵓⵖⵜ ⵙⴳ ⵜⴱⴱⵓⵔⵜ.",
        body: [
          "ⴷⴼⴼⵉⵔ ⵜⴰⵙⵓⵔⵉⴼⵜ ⵏ ⵓⵔⵎ ⴳ ⵜⵎⴷⵉⵏⵉⵏ ⵜⵉⵎⵇⵕⴰⵏⵉⵏ ⵏ ⵜⴳⵍⴷⵉⵜ, ⵜⴰⵅⵍⴰⵚⵜ ⴳ ⵜⵉⵏⵜⵉⵔⵏⵉⵜ ⵏ ⵜⵙⵎⴹⵍⵜ ⵏ ⵜⵎⵣⴷⵓⵖⵜ ⵜⵍⵍⴰ ⴷⵖⵉ ⴳ 200 ⵏ ⵜⵖⵔⵎⵉⵡⵉⵏ ⵜⵉⵎⴰⵢⵏⵓⵜⵉⵏ.",
          "ⵉⵎⵙⵙⵎⵔⴰⵙⵏ ⵣⵎⵔⵏ ⴰⴷ ⵥⵕⵏ ⴰⵙⵙⴰⵖ, ⴰⴷ ⴰⵣⴷⵎⵏ ⴰⵙⴰⴹⵓⴼ ⵏ ⵜⵙⵎⴹⵍⵜ ⴷ ⴰⴷ ⵅⵍⵚⵏ ⵙ ⵜⴽⴰⵕⴹⴰ ⵜⴰⴱⴰⵏⴽⵉⵜ, ⴱⵍⴰ ⴰⴷ ⵜⵜⵓⵔⵏ.",
          "ⴰⵙⵎⵓⵜⵜⵉ ⴰⴷ ⵢⴽⵎⵎⵍ ⴳ ⵉⵢⵢⵓⵔⵏ ⵉⴹⴼⴰⵕⵏ, ⵃⵎⴰ ⴰⴷ ⵜⵜⵡⴰⵙⵎⴹⵏⵜ ⵜⵖⵔⵎⵉⵡⵉⵏ ⴽⵓⵍⵍⵓⵜ ⵏ ⵜⴳⵍⴷⵉⵜ ⵇⴱⵍ 2027.",
        ],
      },
      {
        id: "vigilance-sites-frauduleux",
        date: "20/08/2026",
        category: "ⵜⴰⵎⴰⴳⵉⵜ",
        title: "ⴰⵙⵉⴳⴳⵍ ⵏ ⵓⵃⴻⴹⴹⵓ ⵣⵉ ⵉⵙⵉⵜⵏ ⵉⵎⴰⴽⵔⵏ",
        summary: "ⵜⵜⵡⴰⵙⵙⴽⵏⵜ ⵙⵎⵎⵓⵙ ⵏ ⵜⵎⵍⵖⴰⵢⵉⵏ ⵅⴼ ⵉⵙⵉⵜⵏ ⵉⵎⴰⴽⵔⵏ. ⴰⵣⵎⴻⵎⵎⵉ ⵏ ⵉⵎⵔⵎⵓⵜⵏ ⵉⴼⵓⵍⴽⵉⵏ ⵃⵎⴰ ⴰⴷ ⵜⵜⵡⴰⵃⴹⴰⵏ ⵉⵎⵙⵙⵎⵔⴰⵙⵏ.",
        body: [
          "ⴳ ⵉⵎⴰⵍⴰⵙⵙ ⵉⵣⵔⵉⵏ, ⵜⵜⵡⴰⵙⵙⴽⵏⵜ ⵙⵎⵎⵓⵙ ⵏ ⵉⵙⵉⵜⵏ ⵉⵎⴰⴽⵔⵏ ⵢⵜⵜⴰⵔⵔⴰⵏ ⵜⴰⵍⵖⴰ ⵏ ⵜⴱⴱⵓⵔⵜ ⵜⴰⵏⴰⵎⵓⵔⵜ. ⵉⵙⵉⵜⵏ ⴰ ⵜⵜⴰⵔⵔⴰⵏ ⵜⵉⵎⵢⵓⵔⵉⵏ ⵉⵜⵜⵓⵅⵍⵍⵚⵏ, ⵎⴰⵛⴰ ⴳ ⵜⵉⴷⵜ ⴱⴰⵛⵉ ⵙ ⵢⴰⵏ.",
          "ⵜⴱⴱⵓⵔⵜ ⵜⴰⵏⴰⵎⵓⵔⵜ ⵜⵙⴽⵜⵉ ⵎⴰⵙ ⴽⵓⵍⵍⵓ ⵜⵏⴰⴼⵓⵜⵉⵏ ⵏⵏⵙ ⴱⴰⵛⵉ ⵙ ⵢⴰⵏ, ⴷ ⵓⵔ ⵜⵍⵍⵉⵏⵜ ⴰⵔ ⴳ ⵉⵙⵉⵜⵏ ⵢⵜⵜⴰⵎⵎⴰⵏ ⵙ gov.ma.",
          "ⵎⴰⵔ ⵜⵍⵍⴰ ⵜⵓⴳⵜ, ⵉⵎⵙⵙⵎⵔⴰⵙⵏ ⵜⵜⵡⴰⵜⵜⵔⵏ ⴰⴷ ⵥⵕⵏ ⴰⵙⵙⴰⵖ, ⵓⵔ ⵜⵜⵎⵍⵍⵓⵏ ⵉⵙⴰⴹⵓⴼⵏ ⵏⵏⵙⵏ ⵙ ⵉⵎⴰⵢⵍ ⵏⵖ ⵓⵜⵉⵍⵉⴼⵓⵏ, ⴷ ⴰⴷ ⵙⵙⴽⵏⵏ ⴰⵙⵉⵜ ⴰⵎⴰⴽⵔ ⴳ ⵜⴰⵡⵉⵙⵉ.",
        ],
      },
    ],
    servicesTitle: "ⵜⵉⵏⴰⴼⵓⵜⵉⵏ ⴳ ⵜⵉⵏⵜⵉⵔⵏⵉⵜ ⵏⵏⴰ ⵢⵍⵍⴰⵏ ⴰⴷ ⵜⵜⵓⵙⵏⵏ",
    services: [
      {
        slug: "acte-de-naissance",
        title: "ⵜⴰⵏⴼⴰⵙⵜ ⵏ ⵜⵍⴰⵍⵉⵜ",
        ministry: "ⵜⴰⵎⴰⵡⴰⵙⵜ ⵏ ⴳⵍⵎⵉⵎ",
        theme: "ⵜⵓⴷⵔⵜ ⵜⴰⴳⴷⵓⴷⴰⵏⵜ",
        summary: "ⵙⵓⵜⵔ ⴷ ⴰⵡⵉ ⵜⴰⵏⴼⴰⵙⵜ ⵏ ⵜⵍⴰⵍⵉⵜ ⵏⵏⴽ ⵉⵜⵜⵓⵥⵕⵥⵎⵏ.",
        online: true,
        free: true,
        duration: "48 ⵏ ⵜⵙⵔⴰⴳⵜ",
        popular: true,
      },
      {
        slug: "renouvellement-cnie",
        title: "ⴰⵙⵎⴰⵢⵏⵓ ⵏ ⵜⴽⴰⵕⴹⴰ ⵜⴰⵏⴰⵎⵓⵔⵜ",
        ministry: "ⵜⴰⵎⴰⵡⴰⵙⵜ ⵏ ⴳⵍⵎⵉⵎ — DGSN",
        theme: "ⴰⵎⴰⴳⵏⵓ ⴷ ⵓⵜⵜⵓⵔ",
        summary: "ⵙⵎⴰⵢⵏⵓ ⵜⴰⴽⴰⵕⴹⴰ ⵏⵏⴽ ⵜⴰⵏⴰⵎⵓⵔⵜ ⵇⴱⵍ ⴰⴷ ⵜⵙⴰⵙⵜ.",
        online: true,
        free: false,
        duration: "5 ⵏ ⵡⵓⵙⵙⴰⵏ ⵏ ⵓⵛⵖⴰⵍ",
        popular: true,
      },
      {
        slug: "passeport-biometrique",
        title: "ⴰⵙⴰⵢⵙ ⵏ ⵓⵜⵜⵓⵔ ⴰⴱⵢⵓⵎⵉⵜⵔⵉ",
        ministry: "ⵜⴰⵎⴰⵡⴰⵙⵜ ⵏ ⴳⵍⵎⵉⵎ — DGSN",
        theme: "ⴰⵎⴰⴳⵏⵓ ⴷ ⵓⵜⵜⵓⵔ",
        summary: "ⵙⴽⵔ ⴰⵙⵎⵢⴰⴳⴳⴰⵔ ⴷ ⴹⴼⵕ ⴰⵙⵏⵓⵍⴼⵓ ⵏ ⵓⵙⴰⵢⵙ ⵏⵏⴽ.",
        online: true,
        free: false,
        duration: "8 ⵏ ⵡⵓⵙⵙⴰⵏ ⵏ ⵓⵛⵖⴰⵍ",
        popular: true,
      },
      {
        slug: "carte-grise",
        title: "ⵜⴰⴽⴰⵕⴹⴰ ⵜⴰⵎⵣⵉⵢⴰⵏⵜ",
        ministry: "ⵜⴰⵎⴰⵡⴰⵙⵜ ⵏ ⵓⵙⴼⴰⵔ ⴷ ⵡⴰⵎⴰⵏ",
        theme: "ⵜⵓⴽⴰⵔⵉⵏ ⴷ ⵉⵙⴰⵢⵙⵏ ⵏ ⵓⵙⵉⵜⵜⵍ",
        summary: "ⵙⵎⴹ ⵜⴰⴽⴰⵔⵜ ⵜⴰⵎⴰⵢⵏⵓⵜ ⵏⵖ ⵙⵓⵜⵔ ⵢⴰⵜ ⵜⴰⵏⵜⴰⵍⴰ.",
        online: true,
        free: false,
        duration: "72 ⵏ ⵜⵙⵔⴰⴳⵜ",
        popular: true,
      },
      {
        slug: "attestation-fiscale",
        title: "ⵜⴰⵎⴰⴳⵉⵜ ⵏ ⵜⵙⵎⴹⵍⵜ",
        ministry: "ⵜⴰⵏⴱⴰⴹⵜ ⵜⴰⵎⴰⵜⴰⵢⵜ ⵏ ⵜⵙⵎⴹⴰⵍ",
        theme: "ⵜⵉⵙⵎⴹⴰⵍ",
        summary: "ⴰⵣⴷⵎ ⵜⴰⵎⴰⴳⵉⵜ ⵏ ⵓⵣⴰⴷⵖ ⵏⵏⴽ ⴰⵙⵎⴹⴰⵏ.",
        online: true,
        free: true,
        duration: "ⴷⵖⵉ",
        popular: false,
      },
      {
        slug: "amo",
        title: "ⵜⴰⵎⴰⴳⵉⵜ AMO",
        ministry: "ⵜⴰⵙⵓⵜⵍⵜ ⵜⴰⵏⴰⵎⵓⵔⵜ ⵏ ⵓⵙⵙⴳⵎⵙ ⴰⵏⴰⵎⵓⵏ (CNSS)",
        theme: "ⵜⴰⴷⵓⵙⵉ ⴷ ⵜⵃⵉⵎⴰⵢⵜ ⵜⴰⵏⴰⵎⵓⵏⵜ",
        summary: "ⴰⵣⴷⵎ ⵜⴰⵎⴰⴳⵉⵜ ⵏ ⵓⵙⵙⵉⴷⴼ ⵏⵏⴽ ⴳ ⵜⵓⴹⵏⵜ.",
        online: true,
        free: true,
        duration: "ⴷⵖⵉ",
        popular: true,
      },
    ],
    identityTitle: "ⵢⴰⵜ ⵜⵎⴰⴳⵉⵜ ⵜⴰⵏⴳⵔⴰⵡⴰⵏⵜ ⵉ ⴽⵓⵍⵍⵓ ⵜⵏⴰⴼⵓⵜⵉⵏ ⵏⵏⵓⵏ",
    identityText:
      "ⵙⵏⵓⵍⴼⵓ ⵜⴰⵎⴰⴳⵉⵜ ⵜⴰⵏⴳⵔⴰⵡⴰⵏⵜ ⵜⴰⵏⴰⵎⵓⵔⵜ ⵏⵏⵓⵏ ⴷ ⴽⵛⵎⵜ ⵙ ⵜⴷⵓⵙⵉ ⵖⵔ ⴽⵓⵍⵍⵓ ⵜⵏⴰⴼⵓⵜⵉⵏ, ⴱⵍⴰ ⴰⴷ ⵜⴰⵔⵉⵎ ⵉⵙⴰⴹⵓⴼⵏ ⵏⵏⵓⵏ ⴳ ⵢⴰⵍ ⵜⵎⵢⵓⵔⵜ.",
    identityCta: "ⵙⵏⵓⵍⴼⵓ ⵜⴰⵎⴰⴳⵉⵜ ⵉⵏⵓ ⵜⴰⵏⴳⵔⴰⵡⴰⵏⵜ",
    identityPoints: [
      "ⵢⴰⵏ ⵓⴽⵛⵓⵎ ⵢⵓⵎⵥⵏ ⵖⵔ ⴽⵓⵍⵍⵓ ⵜⵏⴰⴼⵓⵜⵉⵏ ⵜⵉⴳⴷⵓⴷⴰⵏⵉⵏ ⵜⵉⵏⴳⵔⴰⵡⴰⵏⵉⵏ",
      "ⵉⵙⴰⴹⵓⴼⵏ ⵏⵏⵓⵏ ⵉⵜⵜⵓⵥⵕⵥⵎⵏ, ⴷ ⴰⵙⵙⵓⵜⴳ ⵏⵏⵙⵏ ⴰⵙⵙⵓⵜⴳ ⵏ ⵓⵎⴰⴳⵏⵓ",
      "ⴰⴹⴼⴰⵕ ⴰⵢⵓⵎⵥ ⵏ ⵜⵎⵢⵓⵔⵉⵏ ⵏⵏⵓⵏ ⴽⵓⵍⵍⵓⵜ, ⴳ ⵎⴰⵏⵉ ⵜⵍⵍⵉⴹ",
    ],
    appTitle: "ⵜⴰⵏⴱⴰⴹⵜ ⴳ ⵓⴼⵓⵙ ⵏⵏⵓⵏ",
    appText:
      "ⴹⴼⵕ ⵜⵉⵎⵢⵓⵔⵉⵏ ⵏⵏⵓⵏ, ⴰⵡⵉ ⵉⵏⵖⵎⵉⵙⵏ ⴷ ⴰⵣⴷⵎ ⵉⵙⴰⴹⵓⴼⵏ ⵏⵏⵓⵏ ⵉⵏⵚⵉⴱⵏ ⵙⴳ ⵓⵙⵏⴼⴰⵔ ⴰⵏⴰⵎⴱⴰⵢⵍ ⵏ ⵜⴱⴱⵓⵔⵜ ⵜⴰⵏⴰⵎⵓⵔⵜ.",
    appCta: "ⴰⵣⴷⵎ ⴰⵙⵏⴼⴰⵔ",
  },
  procedure: {
    slug: "acte-de-naissance",
    breadcrumb: ["ⵜⴰⵙⵏⴰ ⵜⴰⵎⵣⵡⴰⵔⵓⵜ", "ⵜⵉⵎⵢⵓⵔⵉⵏ", "ⵜⵓⴷⵔⵜ ⵜⴰⴳⴷⵓⴷⴰⵏⵜ"],
    eyebrow: "ⵜⴰⵎⵢⵓⵔⵜ · ⵜⵓⴷⵔⵜ ⵜⴰⴳⴷⵓⴷⴰⵏⵜ",
    title: "ⴰⵙⵓⵜⵔ ⵏ ⵜⵏⴼⴰⵙⵜ ⵏ ⵜⵍⴰⵍⵉⵜ",
    ministry: "ⵜⴰⵎⴰⵡⴰⵙⵜ ⵏ ⴳⵍⵎⵉⵎ — ⵜⴰⵏⴰⵎⵜ ⵜⴰⵎⴰⵜⴰⵢⵜ ⵏ ⵜⵖⵔⵎⵉⵡⵉⵏ",
    summary: "ⴰⵡⵉ ⵜⴰⵏⴼⴰⵙⵜ ⵏ ⵜⵍⴰⵍⵉⵜ ⵏⵏⴽ ⵉⵜⵜⵓⵥⵕⵥⵎⵏ, ⵜⵜⵡⴰⵇⴱⵍⵏ ⵙ ⴽⵓⵍⵍⵓ ⵜⵉⵏⴱⴰⴹⵉⵏ.",
    facts: [
      { label: "ⴰⴽⵓⴷ", value: "48 ⵏ ⵜⵙⵔⴰⴳⵜ" },
      { label: "ⴰⵙⵙⴰⵖ", value: "ⴱⴰⵛⵉ ⵙ ⵢⴰⵏ" },
      { label: "ⴰⵙⵙⵓⵜⴳ", value: "3 ⵏ ⵡⴰⵢⵢⵓⵔⵏ" },
      { label: "ⵉⵎⵙⵙⵎⵔⴰⵙⵏ", value: "ⴽⵓⵍⵍⵓ ⵢⵉⵡⵏ ⵢⵜⵜⵍⴰⵍⵏ ⴳ ⵍⵎⵖⵔⵉⴱ" },
    ],
    tabs: { about: "ⴰⵙⵎⵍ", documents: "ⵉⵙⴰⴹⵓⴼⵏ", steps: "ⵜⵉⵙⵓⵔⵉⴼⵉⵏ", faq: "ⵉⵙⵇⵙⵉⵜⵏ ⵢⵜⵜⵓⵙⵜⵔⵏ ⵓⴳⴳⴰⵔ" },
    about: [
      "ⵜⴰⵏⴼⴰⵙⵜ ⵏ ⵜⵍⴰⵍⵉⵜ ⴷ ⴰⵙⴰⴹⵓⴼ ⵓⵏⵚⵉⴱ ⵢⵓⵎⵥⵏ ⵉⵏⵖⵎⵉⵙⵏ ⵉⵎⵣⵡⵓⵔⴰ ⵏ ⵜⵍⴰⵍⵉⵜ: ⵉⵙⵎ, ⵜⴰⵢⵢⵓⵔⵜ ⴷ ⵜⴰⵎⵣⵡⴰⵔⵓⵜ ⵏ ⵜⵍⴰⵍⵉⵜ, ⴷ ⵜⴰⵙⵓⴽⵜ ⵣⵓⵏⴷ ⵎⴰ ⵉⵜⵜⵓⵙⵓⵜⵔⵏ.",
      "ⴰⵙⴰⴹⵓⴼ ⵢⵜⵜⵓⴼⴽⴰⵏ ⵙⴳ ⵜⴱⴱⵓⵔⵜ ⵉⵜⵜⵓⵥⵕⵥⵎ ⵙⴳ ⵓⵎⵛⵉⵛ ⵏ ⵜⵓⴷⵔⵜ ⵜⴰⴳⴷⵓⴷⴰⵏⵜ ⵏ ⵜⵖⵔⵎⵜ ⵏ ⵜⵍⴰⵍⵉⵜ, ⵢⵜⵜⵓⵎⵍ ⵙ ⵢⴰⵜ ⵜⵅⴰⵜⴰⵎⵜ ⵜⴰⵏⴳⵔⴰⵡⴰⵏⵜ. ⵢⵙⵄⴰ ⵜⴰⴳⴰⵎⴰ ⵜⴰⵙⵏ ⴳⴰⵎⴰⵏ ⵏ ⵓⵙⴰⴹⵓⴼ ⴰⵡⵔⴰⵇ.",
      "ⴰⵙⵓⵜⵔ ⵉⵣⵎⵔ ⴰⴷ ⵢⵜⵜⵓⵙⴽⴰⵔ ⵉ ⵢⵉⵎⴰⵏ ⵏⵏⵓⵏ ⵏⵖ, ⵙ ⵎⴽⵔⴰ ⵏ ⵜⵎⵣⴰⴳⵉⵏ, ⵉ ⵓⵎⵎⵓⵙⵙⵓ ⵏ ⵢⴰⵏ ⵢⵉⴹ. ⴰⴽⵓⴷ ⴰⵎⴰⵜⴰⵢ ⵏ ⵓⵙⵙⵓⵜⵔ ⴷ 48 ⵏ ⵜⵙⵔⴰⴳⵜ ⵉ ⵓⵥⵕⵥⵓⵎ ⴰⵏⴳⵔⴰⵡⴰⵏ.",
    ],
    eligibility: {
      title: "ⵎⵉ ⵢⵣⵎⵔⵏ ⴰⴷ ⵢⵙⴽⵔ ⴰⵙⵓⵜⵔ ⴰ?",
      items: [
        "ⴰⴷ ⵢⵉⵍⵉ ⵉⵜⵜⵍⴰⵍ ⴳ ⵜⵎⵓⵔⵜ ⵏ ⵍⵎⵖⵔⵉⴱ ⴷ ⵢⵙⵄⴰ ⴰⵙⴰⴹⵓⴼ ⵏ ⵜⵍⴰⵍⵉⵜ ⵢⵜⵜⵓⵊⵔⴷⵏ ⴳ ⵉⵎⵥⵍⴰⵢⵏ ⵏ ⵜⵓⴷⵔⵜ ⵜⴰⴳⴷⵓⴷⴰⵏⵜ.",
        "ⴰⴷ ⵢⵎⵍ ⵜⴰⴽⴰⵕⴹⴰ ⵜⴰⵏⴰⵎⵓⵔⵜ ⵜⴰⵏⴳⵔⴰⵡⴰⵏⵜ ⵢⵙⵄⴰⵏ ⴰⵙⵙⵓⵜⴳ.",
        "ⵓⵔ ⵉⵣⵎⵎⵔ ⴰⴷ ⵢⵙⴽⵔ ⵉ ⵢⴰⵏ ⵢⵉⴹ ⵎⴰⵛⴰ ⵙ ⵜⵡⴰⴽⴽⴰⵍⵜ ⵢⵜⵜⵓⵎⵍⵏ.",
        "ⴰⴷ ⵢⵙⵄⵓ ⴰⵎⵉⴹⴰⵏ ⴳ ⵜⵎⴰⴳⵉⵜ ⵜⴰⵏⴳⵔⴰⵡⴰⵏⵜ ⵜⴰⵏⴰⵎⵓⵔⵜ ⵃⵎⴰ ⴰⴷ ⵢⵥⵕⵥⵎ ⴰⵙⵓⵜⵔ.",
      ],
    },
    documents: {
      title: "ⵉⵙⴰⴹⵓⴼⵏ ⵢⵍⵍⴰⵏ ⴰⴷ ⵜⵜⵡⴰⵀⵢⵢⴰⵏ",
      items: [
        { label: "ⵜⴰⴽⴰⵕⴹⴰ ⵜⴰⵏⴰⵎⵓⵔⵜ ⵜⴰⵏⴳⵔⴰⵡⴰⵏⵜ (CNIE)", required: true, hint: "ⵣⴰⵜ ⴷ ⴷⴼⴼⵉⵔ, ⵢⵙⵄⴰ ⴰⵙⵙⵓⵜⴳ" },
        { label: "ⴰⴽⵜⴰⴱ ⵏ ⵜⵡⵊⴰ", required: false, hint: "ⵢⵜⵜⵡⴰⵙⵓⵎⵎⵓⴷ ⵃⵎⴰ ⴰⴷ ⵢⴷⵖⵢⴰ ⵓⵥⵕⵥⵓⵎ ⵏ ⵉⵏⵖⵎⵉⵙⵏ" },
        { label: "ⵜⴰⵡⴰⴽⴽⴰⵍⵜ ⵢⵜⵜⵓⵎⵍⵏ", required: false, hint: "ⵢⵍⵍⴰ ⵓⵃⵜⵜⴰⵊ ⵏⵏⵙ ⵎⴰⵛⴰ ⴰⵙⵓⵜⵔ ⵢⵜⵜⵓⵙⴽⴰⵔ ⵉ ⵢⴰⵏ ⵢⵉⴹ" },
        { label: "ⴰⵙⴰⴹⵓⴼ ⵏ ⵜⴰⵙⵓⴽⵜ", required: false, hint: "ⵢⵜⵜⵡⴰⵔⵏⵓ ⵎⴰⵔ ⵜⵜⵓⵙⵏⴼⵍⵏ ⵉⵏⵖⵎⵉⵙⵏ ⵏ ⵜⵓⴷⵔⵜ ⵜⴰⴳⴷⵓⴷⴰⵏⵜ" },
      ],
    },
    stepsTitle: "ⵎⴰⵎⴽ ⵜⵜⵓⴳⴰⵏ",
    steps: [
      { title: "ⴽⵛⵎ", text: "ⴽⵛⵎ ⵙ ⵜⵎⴰⴳⵉⵜ ⵏⵏⴽ ⵜⴰⵏⴳⵔⴰⵡⴰⵏⵜ ⵜⴰⵏⴰⵎⵓⵔⵜ ⵏⵖ ⵙⵏⵓⵍⴼⵓ ⵜⵉⵙ ⴳ ⵎⵔⴰⵡⵜ ⵏ ⵜⵓⵙⴷⵉⴷⵉⵏ." },
      { title: "ⵜⵜⵔ ⴰⵙⵓⵜⵔ", text: "ⵎⵍ ⵜⴰⵖⵔⵎⵜ ⵏ ⵜⵍⴰⵍⵉⵜ, ⴰⵣⵎⵣ ⵏ ⵜⵏⴼⴰⵙⵜ ⴷ ⵓⵜⴰⵢⵢⵓ ⵏ ⵉⵙⵓⵜⴰⵢⵏ." },
      { title: "ⵥⵕ ⴷ ⵥⵕⵥⵓⵎ", text: "ⵖⵔ ⵜⵉⵏ ⵏ ⵉⵏⵖⵎⵉⵙⵏ ⴷⵖⵉ ⵥⵕⵥⵓⵎ ⴰⵙⵓⵜⵔ ⵏⵏⴽ." },
      { title: "ⴰⵡⵉ ⵜⴰⵏⴼⴰⵙⵜ ⵏⵏⴽ", text: "ⴰⵣⴷⵎ ⴰⵙⴰⴹⵓⴼ ⵏⵏⴽ ⵉⵜⵜⵓⵥⵕⵥⵎⵏ ⵏⵖ ⵙⵜⵉ ⴰⵙⵉⵜⵉ ⴳ ⵜⵖⵔⵎⵜ ⵏⵖ ⴰⵣⵏ ⵙ ⵜⴱⵓⵚⵟⴰ." },
    ],
    faq: [
      {
        q: "ⵎⴰⵏⵜ ⴰⴽⵓⴷ ⵢⵜⵜⵡⴰⵃⵜⴰⵊⵏ ⵃⵎⴰ ⴰⴷ ⴰⵡⵢⵖ ⵜⴰⵏⴼⴰⵙⵜ ⵏ ⵜⵍⴰⵍⵉⵜ?",
        a: "ⴰⵙⴰⴹⵓⴼ ⵢⵜⵜⵓⵜⵜⴽⴰⵏ ⵎⴰⵜⴰⵢⵏ ⴳ 48 ⵏ ⵜⵙⵔⴰⴳⵜ ⵏ ⵓⵛⵖⴰⵍ ⵉ ⵓⵥⵕⵥⵓⵎ ⴰⵏⴳⵔⴰⵡⴰⵏ. ⴰⵙⵉⵜⵉ ⴳ ⵜⵖⵔⵎⵜ ⵏⵖ ⵜⴱⵓⵚⵟⴰ ⵣⵎⵔⵏ ⴰⴷ ⵜⵜⵡⴰⵃⵜⴰⵊⵏ ⴰⴽⵓⴷ ⵢⴰⴹⵏ.",
      },
      {
        q: "ⵉⵙ ⵜⴰⵏⴼⴰⵙⵜ ⵢⵜⵜⵓⴰⵣⴷⵎⵏ ⵜⵙⵄⴰ ⵜⴰⴳⴰⵎⴰ ⵣⵓⵏⴷ ⵜⴰⴳⴰⵎⴰ ⵜⴰⵎⵣⵡⴰⵔⵓⵜ?",
        a: "ⵢⵢⵀ. ⴰⵙⴰⴹⵓⴼ ⵢⵜⵜⵓⵥⵕⵥⵎ ⵙⴳ ⵓⵎⵛⵉⵛ ⵏ ⵜⵓⴷⵔⵜ ⵜⴰⴳⴷⵓⴷⴰⵏⵜ ⴷ ⵢⵙⵄⴰ ⵜⴰⴳⴰⵎⴰ ⵜⴰⵙⵏ ⴳⴰⵎⴰⵏ ⵏ ⵓⵙⴰⴹⵓⴼ ⴰⵡⵔⴰⵇ.",
      },
      {
        q: "ⵉⵙ ⵣⵎⵔⵖ ⴰⴷ ⵙⴽⵔⵖ ⴰⵙⵓⵜⵔ ⵉ ⵢⴰⵏ ⵢⴳⵎⴰ ⵉⵏⵓ?",
        a: "ⵢⵢⵀ, ⵎⴰⵔ ⵜⵔⵏⵓⴷ ⵜⴰⵡⴰⴽⴽⴰⵍⵜ ⵢⵜⵜⵓⵎⵍⵏ ⴷ ⵜⴰⵏⵜⴰⵍⴰ ⵏ ⵜⴽⴰⵕⴹⴰ ⵏ ⵢⵉⵎⴰⵏ ⵏ ⵢⵉⴹ ⵉⵎⵎⵓⵙⵙⵓⵏ.",
      },
      {
        q: "ⵎⴰ ⴰⴷ ⵙⴽⵔⵖ ⵎⴰⵔ ⴰⵙⴰⴹⵓⴼ ⵏ ⵜⵍⴰⵍⵉⵜ ⵉⵏⵓ ⵢⵙⵄⴰ ⴰⵣⴳⵍ?",
        a: "ⵢⵍⵍⴰ ⵓⵃⵜⵜⴰⵊ ⵏ ⵓⵙⵓⵜⵔ ⵏ ⵓⵥⵕⵥⵓⵎ ⵣⴰⵜ ⴳ ⵜⵖⵔⵎⵜ ⵏⵖ ⵜⴰⵎⵀⴽⴰⵎⵜ ⵢⵣⴷⵉⵏ ⵇⴱⵍ ⴰⴷ ⵜⴰⵡⵢⴹ ⵜⴰⵏⴼⴰⵙⵜ ⵢⵜⵜⵓⵥⵕⵥⵎⵏ.",
      },
    ],
    warning: {
      title: "ⵃⴹⵓ ⵙⴳ ⵉⵙⵉⵜⵏ ⵉⵎⴰⴽⵔⵏ",
      text: "ⵜⴰⵏⴰⴼⵓⵜ ⴰ ⴱⴰⵛⵉ ⵙ ⵢⴰⵏ ⴷ ⵜⵍⵍⴰ ⴰⵔ ⴳ ⵉⵙⵉⵜⵏ ⵢⵜⵜⵓⵙⵏⵏ s gov.ma. ⵓⵔ ⵜⵜⵎⵍ ⴰⵔⴰ ⵉⵙⴰⴹⵓⴼⵏ ⵏⵖ ⵉⵏⵖⵎⵉⵙⵏ ⵉⴱⴰⵏⴽⵉⵢⵏ ⵏⵏⴽ ⴳ ⵢⴰⵏ ⵢⴰⴹⵏ ⴰⵙⵉⵜ.",
    },
    form: {
      title: "ⴰⵙⵓⵜⵔ ⴰⵎⴰⵢⵏⵓ ⵏ ⵜⵏⴼⴰⵙⵜ ⵏ ⵜⵍⴰⵍⵉⵜ",
      steps: [
        {
          title: "ⴰⵎⴰⴳⵏⵓ ⵏ ⵓⵎⵙⵓⵜⵔ",
          fields: [
            { kind: "text", name: "nom", label: "ⵉⵙⵎ ⵏ ⵜⵡⵊⴰ", required: true },
            { kind: "text", name: "prenom", label: "ⵉⵙⵎ", required: true },
            { kind: "text", name: "cnie", label: "ⵓⵟⵟⵓⵏ ⵏ CNIE", hint: "ⵜⴰⵍⵖⴰ: A123456", required: true, placeholder: "A123456" },
            { kind: "date", name: "dateNaissance", label: "ⴰⵣⵎⵣ ⵏ ⵜⵍⴰⵍⵉⵜ", required: true },
            { kind: "email", name: "email", label: "ⵉⵎⴰⵢⵍ", required: true },
            { kind: "tel", name: "telephone", label: "ⵓⵜⵉⵍⵉⴼⵓⵏ", required: true, addonStart: "+212" },
          ],
        },
        {
          title: "ⵜⴰⵏⴼⴰⵙⵜ ⵢⵜⵜⵓⵙⵓⵜⵔⵏ",
          fields: [
            {
              kind: "select",
              name: "communeNaissance",
              label: "ⵜⴰⵖⵔⵎⵜ ⵏ ⵜⵍⴰⵍⵉⵜ",
              required: true,
              options: [
                { value: "rabat", label: "ⵕⵕⴱⴰⵟ" },
                { value: "casablanca", label: "ⴰⵏⴼⴰ" },
                { value: "fes", label: "ⴼⴰⵙ" },
                { value: "marrakech", label: "ⵎⵕⵕⴰⴽⵛ" },
                { value: "tanger", label: "ⵟⴰⵏⵊⴰ" },
                { value: "agadir", label: "ⴰⴳⴰⴷⵉⵔ" },
                { value: "sale", label: "ⵙⵍⴰ" },
                { value: "meknes", label: "ⵎⴽⵏⴰⵙ" },
              ],
            },
            {
              kind: "radio",
              name: "typeExtrait",
              label: "ⴰⵣⵎⵣ ⵏ ⵜⵏⴼⴰⵙⵜ",
              required: true,
              options: [
                { value: "extrait-integral", label: "ⵜⴰⵏⴼⴰⵙⵜ ⵎⵎⴰⵍⵏ ⵜⴰⵙⵓⴽⵜ", hint: "ⵜⵓⵎⵥ ⵉⵏⵖⵎⵉⵙⵏ ⴽⵓⵍⵍⵓ ⵏ ⵓⵙⴰⴹⵓⴼ, ⴷ ⵜⴰⵙⵓⴽⵜ" },
                { value: "extrait-simple", label: "ⵜⴰⵏⴼⴰⵙⵜ ⵜⴰⴼⵙⵙⴰⵢⵜ", hint: "ⵜⵓⵎⵥ ⴰⵔ ⵉⵏⵖⵎⵉⵙⵏ ⵉⵎⵣⵡⵓⵔⴰ: ⵉⵙⵎ, ⴰⵣⵎⵣ ⴷ ⵜⴰⵖⵔⵎⵜ ⵏ ⵜⵍⴰⵍⵉⵜ" },
                { value: "copie-integrale", label: "ⵜⴰⵏⵜⴰⵍⴰ ⵢⵎⵎⴰⵜⵜⴰⵏ", hint: "ⵜⴰⵏⵜⴰⵍⴰ ⵢⵎⵎⴰⵜⵜⴰⵏ ⴷ ⵓⵙⴰⴹⵓⴼ ⴰⵎⵣⵡⴰⵔⵓ ⵙ ⵉⵏⵖⵎⵉⵙⵏ ⴽⵓⵍⵍⵓⵜⵏ" },
              ],
            },
            {
              kind: "select",
              name: "nombreExemplaires",
              label: "ⴰⵜⴰⵢⵢⵓ ⵏ ⵉⵙⵓⵜⴰⵢⵏ",
              required: true,
              options: [
                { value: "1", label: "1" },
                { value: "2", label: "2" },
                { value: "3", label: "3" },
                { value: "4", label: "4" },
                { value: "5", label: "5" },
              ],
            },
            {
              kind: "select",
              name: "motif",
              label: "ⵙⴱⴱⴰ ⵏ ⵓⵙⵓⵜⵔ",
              required: true,
              options: [
                { value: "renouvellement-cnie", label: "ⴰⵙⵎⴰⵢⵏⵓ ⵏ CNIE" },
                { value: "passeport", label: "ⴰⵙⵓⵜⵔ ⵏ ⵓⵙⴰⵢⵙ ⵏ ⵓⵜⵜⵓⵔ" },
                { value: "mariage", label: "ⴰⴼⴰⵢⵍⵓ ⵏ ⵣⵡⴰⵊ" },
                { value: "inscription-scolaire", label: "ⴰⵙⵎⵜⵉ ⴳ ⵜⵉⵏⵎⵍ ⵏⵖ ⵜⴰⵙⴷⴰⵡⵉⵜ" },
                { value: "autre", label: "ⵙⴱⴱⴰ ⵢⴰⴹⵏ" },
              ],
            },
            { kind: "checkbox", name: "pourTiers", label: "ⴰⵙⵓⵜⵔ ⴰ ⵢⵜⵜⵓⵙⴽⴰⵔ ⵉ ⵢⴰⵏ ⵢⵉⴹ" },
            { kind: "file", name: "pieceJointe", label: "ⴰⵙⴰⴹⵓⴼ ⵢⵜⵜⵓⵔⵏⵓⵏ", hint: "ⵜⴰⵡⴰⴽⴽⴰⵍⵜ ⵏⵖ ⴰⵙⴰⴹⵓⴼ, ⵎⴰⵔ ⵢⵍⵍⴰ ⵓⵃⵜⵜⴰⵊ", accept: ".pdf,.jpg" },
          ],
        },
        {
          title: "ⴰⵙⵉⵜⵉ",
          fields: [
            {
              kind: "radio",
              name: "modeReception",
              label: "ⴰⵔⵔⴰ ⵏ ⵓⵙⵉⵜⵉ",
              required: true,
              options: [
                { value: "pdf-email", label: "PDF ⵢⵜⵜⵓⵥⵕⵥⵎⵏ ⵙ ⵉⵎⴰⵢⵍ", hint: "ⵢⵜⵜⵡⴰⵜⵜⴽ ⴷⵖⵉ ⵙ ⵉⵎⴰⵢⵍ ⵎⵍⵎⵉ ⵢⵎⵎⵓⵜⵜⴰ ⵓⵙⴰⴹⵓⴼ" },
                { value: "retrait-commune", label: "ⴰⵙⵉⵜⵉ ⴳ ⵜⵖⵔⵎⵜ", hint: "ⵢⵜⵜⵓⵙⵜⵉ ⵙⴳ ⵓⵙⵉⵜⵉ ⵏ ⵜⵖⵔⵎⵜ ⵏ ⵜⵍⴰⵍⵉⵜ" },
                { value: "courrier-postal", label: "ⴰⵣⵏ ⵙ ⵜⴱⵓⵚⵟⴰ", hint: "ⴰⴽⵓⴷ ⵢⴰⴹⵏ ⵏ 3 ⴰⵔ 5 ⵏ ⵡⵓⵙⵙⴰⵏ ⵏ ⵓⵛⵖⴰⵍ" },
              ],
            },
            { kind: "text", name: "adresse", label: "ⵜⴰⵏⵙⴰ ⵏ ⵓⵙⵉⵜⵉ", hint: "ⵢⵜⵜⵡⴰⵙⵓⵜⵔ ⴰⵔ ⵎⴰⵔ ⵢⵍⵍⴰ ⵓⵣⵏ ⵙ ⵜⴱⵓⵚⵟⴰ" },
          ],
        },
      ],
      reviewTitle: "ⵥⵕⵥⵓⵎ ⴰⵙⵓⵜⵔ ⵏⵏⴽ",
      reviewText: "ⵖⵔ ⵜⵉⵏ ⵏ ⵉⵏⵖⵎⵉⵙⵏ ⵢⵜⵜⵓⴰⵔⵉⵏ ⵣⴰⵜ ⴰⴷ ⵜⵥⵕⵥⵎⴹ ⴷ ⴰⴷ ⵜⵙⵙⵉⴼⴹⴹ ⴰⵙⵓⵜⵔ ⵏⵏⴽ. ⴰⵣⴳⵍ ⴰⵔⴰ ⵢⵣⵎⵔⵏ ⴰⴷ ⵢⵄⵟⵜⵍ ⴰⵙⵎⵢⴰⵡⴰⴹ ⵏⵏⵙ.",
      consent: "ⵜⵜⴳⴰⵖ ⴰⴷ ⵉⵍⵉⵏⵜ ⵉⵏⵖⵎⵉⵙⵏ ⵜⴰⵎⵢⴰⴳⵉⵜ ⴷ ⵇⴱⵍⵖ ⵉⵙⵎⵜⴰⵔⵏ ⵉⵎⴰⵜⴰⵢⵏ ⵏ ⵓⵙⵎⵔⵙ ⵏ ⵜⵏⴰⴼⵓⵜ ⴰ.",
      submit: "ⵙⵙⵉⴼⴹ ⴰⵙⵓⵜⵔ ⵉⵏⵓ",
      previous: "ⵉⵣⵡⴰⵔⵏ",
      next: "ⴰⴹⴼⴰⵕ",
      saveDraft: "ⵣⴷⵍ ⵣⵓⵏⴷ ⴰⵔⵎⵎⵓⵙ",
      draftSavedText: "ⵉⵜⵜⵓⵃⴹⴰ ⵖⴰⵙ ⴳ ⵓⵎⴰⵙⵙ ⴰⴷ — ⴰⵙⴽⴰⵏ, ⵓⵔ ⵉⵜⵜⵓⵣⵏ ⵡⴰⵍⵓ.",
      draftFound: "ⵉⵜⵜⵓⵃⴹⴰ ⵢⴰⵏ ⵓⵔⵎⵎⵓⵙ ⴳ ⵓⵎⴰⵙⵙ ⴰⴷ.",
      resumeDraft: "ⴰⵍⵙ ⵉ ⵓⵔⵎⵎⵓⵙ",
      success: {
        title: "ⴰⵙⵓⵜⵔ ⵏⵏⴽ ⵢⵜⵜⵓⵙⵙⵉⴼⴹ",
        text: "ⴰⴷ ⵜⴰⵡⵢⴹ ⵢⴰⵏ ⵓⵏⵖⵎⵉⵙ ⵎⵍⵎⵉ ⵜⵎⵎⵓⵜⵜⴰ ⵜⴰⵏⴼⴰⵙⵜ ⵏⵏⴽ. ⵜⵣⵎⵔⴹ ⴰⴷ ⵜⴹⴼⵕⴹ ⴰⵎⵢⵓⵔ ⵏ ⵓⵙⵓⵜⵔ ⵏⵏⴽ ⵙⴳ ⵓⵎⵉⴹⴰⵏ ⵏⵏⴽ.",
        reference: "ⵓⵟⵟⵓⵏ 2026-04512",
        nextSteps: [
          "ⴰⴷ ⵜⴰⵡⵢⴹ ⵢⴰⵏ ⵉⵎⴰⵢⵍ ⵢⵙⵙⴽⵏⵏ ⵓⵟⵟⵓⵏ ⵏ ⵓⴹⴼⴰⵕ ⵏ ⵓⵙⵓⵜⵔ ⵏⵏⴽ.",
          "ⴰⵎⵛⵉⵛ ⵏ ⵜⵓⴷⵔⵜ ⵜⴰⴳⴷⵓⴷⴰⵏⵜ ⵏ ⵜⵖⵔⵎⵜ ⵏ ⵜⵍⴰⵍⵉⵜ ⵢⵥⵕⵥⵓⵎ ⴰⵙⵓⵜⵔ ⵏⵏⴽ ⴳ 48 ⵏ ⵜⵙⵔⴰⴳⵜ.",
          "ⴰⴷ ⵜⵜⵡⴰⵙⵙⴽⵏⴹ ⵙ ⵢⴰⵏ ⵓⵏⵖⵎⵉⵙ ⵎⵍⵎⵉ ⵢⵎⵎⵓⵜⵜⴰ ⵓⵙⴰⴹⵓⴼ ⵢⵜⵜⵓⵥⵕⵥⵎⵏ ⵃⵎⴰ ⴰⴷ ⵢⵜⵜⵓⴰⵣⴷⵎ.",
        ],
        download: "ⴰⵣⴷⵎ ⴰⵏⵖⵎⵉⵙ ⵏ ⵓⵙⵉⵜⵉ",
        track: "ⴹⴼⵕ ⴰⵙⵓⵜⵔ ⵉⵏⵓ",
      },
    },
  },
  ministry: {
    breadcrumb: ["ⵜⴰⵙⵏⴰ ⵜⴰⵎⵣⵡⴰⵔⵓⵜ", "ⵜⵉⵖⵔⵎⵉⵡⵉⵏ", "ⵜⴰⵎⴰⵡⴰⵙⵜ ⵏ ⵓⵙⵎⵓⵜⵜⵉ ⴰⵎⵙⵙⵏⴳⴰⵍ ⴷ ⵓⵚⵍⵍⴰⵃ ⵏ ⵜⵏⴱⴰⴹⵜ"],
    name: "ⵜⴰⵎⴰⵡⴰⵙⵜ ⵏ ⵓⵙⵎⵓⵜⵜⵉ ⴰⵎⵙⵙⵏⴳⴰⵍ ⴷ ⵓⵚⵍⵍⴰⵃ ⵏ ⵜⵏⴱⴰⴹⵜ",
    short: "MTNRA",
    mission:
      "ⵜⴰⵎⴰⵡⴰⵙⵜ ⵏ ⵓⵙⵎⵓⵜⵜⵉ ⴰⵎⵙⵙⵏⴳⴰⵍ ⴷ ⵓⵚⵍⵍⴰⵃ ⵏ ⵜⵏⴱⴰⴹⵜ ⵜⵜⵓⵎⵥ ⵜⴰⵙⵜⵔⴰⵜⵉⵊⵉⵜ ⵏ ⵓⵙⵎⵓⵜⵜⵉ ⴰⵎⵙⵙⵏⴳⴰⵍ ⵏ ⵜⵏⴰⴼⵓⵜⵉⵏ ⵜⵉⴳⴷⵓⴷⴰⵏⵉⵏ. ⵜⵙⵙⵎⵢⴰⴳⴳⴰⵔ ⴰⴼⵙⵙⵓ ⵏ ⵉⵎⵢⵓⵔⵏ, ⴰⵎⵢⴰⵡⴰⴹ ⴳⵔ ⵉⵏⴳⵔⴰⵡⵏ ⵏ ⵜⵏⴱⴰⴹⵜ ⴷ ⵓⵙⵎⵓⵜⵜⵉ ⵏ ⵜⵎⴰⴳⵉⵜ ⵜⴰⵏⴳⵔⴰⵡⴰⵏⵜ ⵜⴰⵏⴰⵎⵓⵔⵜ.",
    missionsTitle: "ⵜⵉⵎⵓⵔⴰ ⵏⵏⵖ",
    missions: [
      {
        title: "ⴰⴼⵙⵙⵓ ⵏ ⵉⵎⵢⵓⵔⵏ",
        text: "ⴰⴷⵖⵢⴰ ⵏ ⵉⴽⵓⴷⵏ ⴷ ⵓⵟⵟⵓⵏ ⵏ ⵉⵙⴰⴹⵓⴼⵏ ⵢⵜⵜⵓⵙⵓⵜⵔⵏ ⴳ ⵢⴰⵍ ⵜⴰⵎⵢⵓⵔⵜ.",
      },
      {
        title: "ⴰⵙⴼⴰⵛ ⵏ ⵜⵏⴰⴼⵓⵜⵉⵏ ⴳ ⵜⵉⵏⵜⵉⵔⵏⵉⵜ",
        text: "ⴰⵙⴽⵔ ⵏ ⴽⵓⵍⵍⵓ ⵜⵎⵢⵓⵔⵉⵏ ⵉⵜⵜⵓⵙⵓⵜⵔⵏ ⵓⴳⴳⴰⵔ ⴳ ⵜⴱⴱⵓⵔⵜ ⵜⴰⵏⴰⵎⵓⵔⵜ.",
      },
      {
        title: "ⴰⵣⴷⴰⵢ ⵏ ⵜⵎⴰⴳⵉⵜ ⵜⴰⵏⴳⵔⴰⵡⴰⵏⵜ",
        text: "ⴰⵙⵙⴼⵍⴷ ⵉ ⵢⴰⵍ ⴰⵖⵔⴼ ⴰⴷ ⵢⵙⴽⵔ ⴰⵎⵢⴰⴳⴳⴰⵔ ⵢⴰⵏ ⵓⴽⵓⴷ ⵃⵎⴰ ⴰⴷ ⵢⴽⵛⵎ ⵖⵔ ⴽⵓⵍⵍⵓ ⵜⵏⴰⴼⵓⵜⵉⵏ.",
      },
      {
        title: "ⴰⵕⵥⵎ ⵏ ⵉⵙⴰⴹⵓⴼⵏ ⵉⴳⴷⵓⴷⴰⵏⵏ",
        text: "ⴰⵙⵎⵓⵜⵜⴳ ⴷ ⵓⵙⵏⵓⵍⴼⵓ ⵙ ⵓⵕⵥⵎ ⵏ ⵉⵙⴰⴹⵓⴼⵏ ⵓⵔ ⵉⵎⵥⵍⴰⵢⵏ.",
      },
    ],
    servicesTitle: "ⵜⵉⵏⴰⴼⵓⵜⵉⵏ ⴳ ⵜⵉⵏⵜⵉⵔⵏⵉⵜ ⵏ ⵜⵎⴰⵡⴰⵙⵜ",
    services: [
      { label: "ⵜⴰⴱⴱⵓⵔⵜ ⵜⴰⵏⴰⵎⵓⵔⵜ ⵏ ⵜⵏⴰⴼⵓⵜⵉⵏ ⵜⵉⴳⴷⵓⴷⴰⵏⵉⵏ", href: "/", description: "ⴽⵓⵍⵍⵓ ⵜⵉⵎⵢⵓⵔⵉⵏ ⴳ ⵢⴰⵜ ⵜⵍⵍⵉⵜ" },
      { label: "Idarati.ma", href: "https://www.idarati.ma", description: "ⴰⵎⵓⵔⴰ ⵏ ⵜⵎⵢⵓⵔⵉⵏ ⴷ ⵉⵙⴰⴹⵓⴼⵏ" },
      { label: "Chikaya.ma", href: "https://www.chikaya.ma", description: "ⵙⵙⵉⴼⴹ ⵜⴰⵎⴰⵜⴰⵔⵜ ⵉ ⵜⵏⴱⴰⴹⵜ" },
      { label: "ⵉⵙⴰⴹⵓⴼⵏ ⵢⵕⵥⵎⵏ", href: "https://data.gov.ma", description: "ⵜⴰⵖⴹⴼⵜ ⵏ ⵉⵙⴰⴹⵓⴼⵏ ⵉⴳⴷⵓⴷⴰⵏⵏ" },
      { label: "ⵜⴰⵎⴰⴳⵉⵜ ⵜⴰⵏⴳⵔⴰⵡⴰⵏⵜ ⵜⴰⵏⴰⵎⵓⵔⵜ", href: "/aide", description: "ⵙⵏⵓⵍⴼⵓ ⴷ ⵙⵡⵓⴹⴹⵓ ⵜⴰⵎⴰⴳⵉⵜ ⵏⵏⴽ" },
      { label: "ⴰⵥⵕⵥⵓⵎ ⴰⵏⴳⵔⴰⵡⴰⵏ", href: "/aide", description: "ⵥⵕⵥⵓⵎ ⵉⵙⴰⴹⵓⴼⵏ ⵏⵏⴽ ⴳ ⵜⵉⵏⵜⵉⵔⵏⵉⵜ" },
    ],
    figures: [
      { value: "540", label: "ⵜⴰⵏⴰⴼⵓⵜ ⴳ ⵜⵉⵏⵜⵉⵔⵏⵉⵜ" },
      { value: "1200", label: "ⵜⴰⵖⵔⵎⵜ ⵣⴷⵉⵜ ⴷ ⵜⴱⴱⵓⵔⵜ" },
      { value: "3,2 ⵎ", label: "ⵜⴰⵎⴰⴳⵉⵜ ⵜⴰⵏⴳⵔⴰⵡⴰⵏⵜ ⵜⵙⴽⵔⵏ" },
      { value: "98%", label: "ⴰⵣⴷⴰⵢ ⵏ ⵓⵙⵎⵓⵜⵜⴳ" },
    ],
    newsTitle: "ⵉⵏⵖⵎⵉⵙⵏ ⵏ ⵜⵎⴰⵡⴰⵙⵜ",
    organisationTitle: "ⴰⵙⵎⵓⵜⵜⴳ",
    organisation: [
      {
        title: "ⵜⴰⵎⴰⵙⵙⴰⵏⵜ ⵏ ⵓⵙⵏⴼⵍ ⴰⵎⵙⵙⵏⴳⴰⵍ (ADD)",
        text: "ⵜⵙⵙⵎⵢⴰⴳⴳⴰⵔ ⵜⴰⵙⵜⵔⴰⵜⵉⵊⵉⵜ ⵜⴰⵏⴰⵎⵓⵔⵜ ⵏ ⵓⵙⵎⵓⵜⵜⵉ ⴰⵎⵙⵙⵏⴳⴰⵍ ⴷ ⵜⴰⵡⵉⵙⵉ ⵏ ⵜⵏⴱⴰⴹⵉⵏ.",
      },
      {
        title: "ⵜⴰⵏⴰⵎⵜ ⵏ ⵓⵚⵍⵍⴰⵃ ⵏ ⵜⵏⴱⴰⴹⵜ",
        text: "ⵜⵙⵙⵎⵢⴰⴳⴳⴰⵔ ⴰⴼⵙⵙⵓ ⵏ ⵉⵎⵢⵓⵔⵏ ⴷ ⵓⵙⵏⴼⵍ ⵏ ⵜⴳⵎⵉ ⴳⵔ ⵜⵏⴱⴰⴹⵜ ⴷ ⵉⵎⵙⵙⵎⵔⴰⵙⵏ.",
      },
      {
        title: "ⵜⴰⵏⴰⵎⵜ ⵏ ⵉⵏⴳⵔⴰⵡⵏ ⵏ ⵜⵏⴱⴰⴹⵜ",
        text: "ⵜⵙⵙⵓⵎⵎⵓⴷ ⴰⵎⵢⴰⵡⴰⴹ ⴳⵔ ⵉⵏⴳⵔⴰⵡⵏ ⴷ ⵜⴰⴷⴰⵎⵙⴰ ⵏ ⵜⴼⵍⴰⵜⵉⵏ ⵜⵉⴳⴷⵓⴷⴰⵏⵉⵏ.",
      },
      {
        title: "ⵜⴰⵙⵉⵏⴰⴳⵜ ⵜⴰⵎⴰⵜⴰⵢⵜ ⵏ ⵜⵏⴱⴰⴹⵜ",
        text: "ⵜⵙⵙⵎⵓⵜⵜⴳ ⵉⵎⴳⴳⵉⵢⵏ ⵏ ⵜⵎⵃⴹⴰⵔⵜ ⵜⴰⴳⴷⵓⴷⴰⵏⵜ ⴳ ⵜⵎⵢⵓⵔⵉⵏ ⵜⵉⵏⴳⵔⴰⵡⴰⵏⵉⵏ.",
      },
    ],
    contactTitle: "ⵏⵎⵎⴰⵖⴰⵜ ⴷⵉⴷⵏⵖ",
    contact: {
      address: "ⵜⴰⵔⵔⴰⵙⵜ ⵏ ⵓⵏⵅⵉⵍ, ⵀⴰⵢ ⵔⵢⴰⴹ, ⵕⵕⴱⴰⵟ",
      phone: "+212 5 37 68 00 00",
      email: "contact@mtnra.gov.ma",
      hours: "ⴰⵢⵏⴰⵙ ⴰⵔ ⵙⵉⵎⵡⴰⵙ, ⵙⴳ 8:30 ⴰⵔ 16:30",
    },
    documentsTitle: "ⵉⵙⵓⴼⵖⵏ",
    documents: [
      { title: "ⴰⵏⵣⴰⵕ ⴰⵙⴳⴳⵯⴰⵙⴰⵏ ⵏ ⵓⵙⵎⵓⵜⵜⵉ ⴰⵎⵙⵙⵏⴳⴰⵍ 2025", format: "PDF", size: "4,2 ⵎⵓ", date: "12/03/2026" },
      { title: "ⵜⴰⵙⵜⵔⴰⵜⵉⵊⵉⵜ ⵜⴰⵏⴰⵎⵓⵔⵜ ⵍⵎⵖⵔⵉⴱ ⴰⵎⵙⵙⵏⴳⴰⵍ 2030", format: "PDF", size: "2,8 ⵎⵓ", date: "05/02/2026" },
      { title: "ⴰⵎⴰⵙⵙⵏ ⵏ ⵓⵙⵎⵔⵙ ⵏ ⵜⴱⴱⵓⵔⵜ ⵜⴰⵏⴰⵎⵓⵔⵜ", format: "PDF", size: "1,1 ⵎⵓ", date: "18/01/2026" },
      { title: "ⴰⵙⴳⵣⵣⵍ ⵏ ⵓⵎⵓⵔⵙ ⵏ ⵉⵎⵙⵙⵎⵔⴰⵙⵏ 2025", format: "PDF", size: "980 ⴽⵓ", date: "30/04/2026" },
    ],
  },
  search: {
    title: "ⵉⵎⵢⴰⵡⴰⴹⵏ ⵏ ⵓⵔⵣⵣⵓ",
    query: "ⵜⴰⵏⴼⴰⵙⵜ ⵏ ⵜⵍⴰⵍⵉⵜ",
    resultsCount: "{count} ⵏ ⵉⵎⵢⴰⵡⴰⴹⵏ ⵅⴼ « {query} »",
    filterThemes: ["ⵜⵓⴷⵔⵜ ⵜⴰⴳⴷⵓⴷⴰⵏⵜ", "ⴰⵎⴰⴳⵏⵓ ⴷ ⵓⵜⵜⵓⵔ", "ⵜⴰⴷⵓⵙⵉ ⴷ ⵜⵃⵉⵎⴰⵢⵜ ⵜⴰⵏⴰⵎⵓⵏⵜ", "ⴰⵙⴳⵎⵉ", "ⴰⵛⵖⴰⵍ ⴷ ⵜⴰⵎⵙⵎⵓⵏⵜ"],
    filterMinistries: [
      "ⵜⴰⵎⴰⵡⴰⵙⵜ ⵏ ⴳⵍⵎⵉⵎ",
      "ⵜⴰⵎⴰⵡⴰⵙⵜ ⵏ ⵜⴷⵓⵙⵉ ⴷ ⵜⵃⵉⵎⴰⵢⵜ ⵜⴰⵏⴰⵎⵓⵏⵜ",
      "ⵜⴰⵎⴰⵡⴰⵙⵜ ⵏ ⵍⴱⵕⵕⴰⵏⵉⵢⵢⴰ, ⵜⴰⵎⵙⵎⵓⵏⵜ ⵏ ⵜⴼⵔⵉⵇⵜ ⴷ ⵉⵎⵖⵔⴰⴱⵉⵢⵏ ⵢⵣⴷⵖⵏ ⴱⵕⵕⴰ",
      "ⵜⴰⵎⴰⵡⴰⵙⵜ ⵏ ⵓⵙⵎⵓⵜⵜⵉ ⴰⵎⵙⵙⵏⴳⴰⵍ ⴷ ⵓⵚⵍⵍⴰⵃ ⵏ ⵜⵏⴱⴰⴹⵜ",
    ],
    results: [
      {
        title: "ⴰⵙⵓⵜⵔ ⵏ ⵜⵏⴼⴰⵙⵜ ⵏ ⵜⵍⴰⵍⵉⵜ",
        href: "/demarches/acte-de-naissance",
        ministry: "ⵜⴰⵎⴰⵡⴰⵙⵜ ⵏ ⴳⵍⵎⵉⵎ",
        summary: "ⴰⵡⵉ ⵜⴰⵏⴼⴰⵙⵜ ⵏ ⵜⵍⴰⵍⵉⵜ ⵏⵏⴽ ⵉⵜⵜⵓⵥⵕⵥⵎⵏ, ⵜⵜⵡⴰⵇⴱⵍⵏ ⵙ ⴽⵓⵍⵍⵓ ⵜⵉⵏⴱⴰⴹⵉⵏ.",
        online: true,
        updated: "10/09/2026",
      },
      {
        title: "ⴰⵥⵕⵥⵓⵎ ⵏ ⵓⵙⴰⴹⵓⴼ ⵏ ⵜⵍⴰⵍⵉⵜ",
        href: "/demarches/rectification-acte-naissance",
        ministry: "ⵜⴰⵎⴰⵡⴰⵙⵜ ⵏ ⴳⵍⵎⵉⵎ",
        summary: "ⵥⵕⵥⵓⵎ ⴰⵣⴳⵍ ⵏⵖ ⴰⵎⵥⵍⵉ ⵢⵜⵜⵓⴰⴼⵏ ⴳ ⵓⵙⴰⴹⵓⴼ ⵏ ⵜⵍⴰⵍⵉⵜ.",
        online: false,
        updated: "03/09/2026",
      },
      {
        title: "ⴰⵙⴰⴹⵓⴼ ⵏ ⵜⵍⴰⵍⵉⵜ ⵉ ⵉⵎⵖⵔⴰⴱⵉⵢⵏ ⵢⵣⴷⵖⵏ ⴱⵕⵕⴰ",
        href: "/demarches/acte-naissance-mre",
        ministry: "ⵜⴰⵎⴰⵡⴰⵙⵜ ⵏ ⵍⴱⵕⵕⴰⵏⵉⵢⵢⴰ, ⵜⴰⵎⵙⵎⵓⵏⵜ ⵏ ⵜⴼⵔⵉⵇⵜ ⴷ ⵉⵎⵖⵔⴰⴱⵉⵢⵏ ⵢⵣⴷⵖⵏ ⴱⵕⵕⴰ",
        summary: "ⵜⵜⵔ ⵜⴰⵏⴼⴰⵙⵜ ⵏ ⵜⵍⴰⵍⵉⵜ ⵙⴳ ⵜⵇⵓⵏⵚⵓⵍⵉⵢⵢⵜ ⵏⵏⴽ ⵏⵖ ⴳ ⵜⵉⵏⵜⵉⵔⵏⵉⵜ.",
        online: true,
        updated: "28/08/2026",
      },
      {
        title: "ⴰⵙⵎⵢⴰⴳⴳⴰⵔ ⵏ ⵉⵙⴰⴹⵓⴼⵏ ⵏ ⵜⵓⴷⵔⵜ ⵜⴰⴳⴷⵓⴷⴰⵏⵜ",
        href: "/demarches/legalisation-document",
        ministry: "ⵜⴰⵎⴰⵡⴰⵙⵜ ⵏ ⴳⵍⵎⵉⵎ",
        summary: "ⵙⴽⵔ ⴰⵙⵎⵢⴰⴳⴳⴰⵔ ⵏ ⵉⵙⴰⴹⵓⴼⵏ ⵏⵏⴽ ⵃⵎⴰ ⴰⴷ ⵜⵏ ⵜⵙⵎⵔⵙⴹ ⴱⵕⵕⴰ.",
        online: false,
        updated: "15/07/2026",
      },
      {
        title: "ⴰⵎⵎⴰⵍⴰ ⵏ ⵜⵍⴰⵍⵉⵜ ⵏ ⵢⴰⵏ ⵓⵃⵏⵊⵉⵕ",
        href: "/demarches/declaration-naissance",
        ministry: "ⵜⴰⵎⴰⵡⴰⵙⵜ ⵏ ⵜⴷⵓⵙⵉ ⴷ ⵜⵃⵉⵎⴰⵢⵜ ⵜⴰⵏⴰⵎⵓⵏⵜ",
        summary: "ⵎⵎⴰⵍ ⵜⴰⵍⴰⵍⵉⵜ ⵏ ⵓⵃⵏⵊⵉⵕ ⵏⵏⴽ ⵉ ⵜⵖⵔⵎⵜ ⴳ ⵉⴽⵓⴷⵏ ⵢⵜⵜⵓⵙⵙⵏⵏ.",
        online: false,
        updated: "05/06/2026",
      },
      {
        title: "ⴰⵎⴰⵙⵙⵏ: ⵎⴰⵎⴽ ⴰⴷ ⵜⴰⵡⵢⴹ ⴰⵙⴰⴹⵓⴼ ⵏ ⵜⵍⴰⵍⵉⵜ",
        href: "/aide/guide-acte-de-naissance",
        ministry: "ⵜⴰⵎⴰⵡⴰⵙⵜ ⵏ ⵓⵙⵎⵓⵜⵜⵉ ⴰⵎⵙⵙⵏⴳⴰⵍ ⴷ ⵓⵚⵍⵍⴰⵃ ⵏ ⵜⵏⴱⴰⴹⵜ",
        summary: "ⵜⵉⵙⵓⵔⵉⴼⵉⵏ ⴽⵓⵍⵍⵓⵜⵉⵏ ⵜⵜⵡⴰⵎⵎⴰⵍⵏⵜ ⵙ ⵜⴼⵙⵙⴰⵢⵜ ⵃⵎⴰ ⴰⴷ ⵜⴰⵡⵢⴹ ⴰⵙⴰⴹⵓⴼ ⵏ ⵜⵍⴰⵍⵉⵜ ⵏⵏⴽ.",
        online: true,
        updated: "01/09/2026",
      },
    ],
    noResults: "ⵓⵔ ⵢⵍⵍⵉ ⵢⴰⵏ ⵓⵎⵢⴰⵡⴰⴹ ⵢⵎⵙⴰⵙⴰⵏ ⴷ ⵓⵔⵣⵣⵓ ⵏⵏⴽ. ⵔⵎ ⵙ ⵉⵎⵙⵜⴰⵢⵏ ⵢⴰⴹⵏⵉⵏ ⵏⵖ ⵥⵕ ⵜⵉⵎⵎⴰⵍⵉⵏ ⵏⵏⵖ ⴰⴷⴰⵢ.",
    suggestions: ["ⵜⴰⵏⵜⴰⵍⴰ ⵢⵎⵎⴰⵜⵜⴰⵏ ⵏ ⵓⵙⴰⴹⵓⴼ ⵏ ⵜⵍⴰⵍⵉⵜ", "ⴰⵥⵕⵥⵓⵎ ⵏ ⵓⵙⴰⴹⵓⴼ ⵏ ⵜⵍⴰⵍⵉⵜ", "ⴰⵙⴰⴹⵓⴼ ⵏ ⵜⵍⴰⵍⵉⵜ ⵉ ⵉⵎⵖⵔⴰⴱⵉⵢⵏ ⵢⵣⴷⵖⵏ ⴱⵕⵕⴰ"],
  },
  news: {
    title: "ⵉⵏⵖⵎⵉⵙⵏ",
    intro: "ⵉⵏⵖⵎⵉⵙⵏ ⴽⵓⵍⵍⵓⵜⵏ ⵏ ⵜⵏⴰⴼⵓⵜⵉⵏ ⵜⵉⴳⴷⵓⴷⴰⵏⵉⵏ ⴷ ⵜⵎⵢⵓⵔⵉⵏ ⴳ ⵜⵉⵏⵜⵉⵔⵏⵉⵜ.",
    categories: ["ⵜⴰⵏⴰⴼⵓⵜ ⵜⴰⵏⴳⵔⴰⵡⴰⵏⵜ", "ⵜⵉⵙⵎⴹⴰⵍ", "ⵜⴰⵎⴰⴳⵉⵜ", "ⴰⴼⵙⵙⵓ"],
  },
  errors: {
    demoStubTitle: "ⵜⴰⵙⵏⴰ ⵓⵔ ⵜⵜⵓⵙⴽⴰⵔ ⴳ ⵓⵙⴽⴰⵏ ⴰⴷ",
    demoStubText: "ⴰⵣⴷⴰⵢ ⴰⴷ ⵉⵍⵍⴰ ⴰⴼⴰⴷ ⴰⴷ ⵉⴳ ⵓⵏⵏⴰⵢ ⴰⵎⴰⵢⵏⵓ, ⵎⴰⵛⴰ ⵜⴰⵙⵏⴰ ⵓⵔ ⵜⵜⵓⴱⵏⴰ. ⵉⴼⵔⴷⵉⵙⵏ ⵉⵍⵍⴰⵏ ⴳ ⵜⵙⵏⵙⵉ ⵏ DSM.",
    notFoundTitle: "ⵜⴰⵙⵏⴰ ⵓⵔ ⵜⵜⵓⴼⵉⵏ",
    notFoundText: "ⵜⴰⵙⵏⴰ ⵏⵏⴰ ⵜⵔⵣⵣⵓⵜ ⵓⵔ ⵜⵍⵍⵉ ⵏⵖ ⵜⵜⵓⵙⵏⴼⵍⵜ. ⵥⵕ ⴰⵙⵙⴰⵖ ⵏⵖ ⵙⵎⵔⵙ ⴰⵔⵣⵣⵓ.",
    serverTitle: "ⵜⴰⵣⴳⵍⵜ ⵢⴹⵕⴰⵏ",
    serverText: "ⵜⴰⵏⴰⴼⵓⵜ ⵜⵓⴼⴰ ⵢⴰⵜ ⵜⵓⴳⴳⴰⵣⵜ ⵜⴰⵜⵉⴽⵏⵉⴽⵜ. ⵄⴰⵡⴷ ⴰⵔⵎ ⴷⴼⴼⵉⵔ ⵎⵛⵛⴰⵏ ⵏ ⵜⵓⵙⴷⵉⴷⵉⵏ.",
    maintenanceTitle: "ⵜⴰⵏⴰⴼⵓⵜ ⵓⵔ ⵜⵍⵍⵉ ⴷⵖⵉ",
    maintenanceText: "ⵜⴰⵙⵏⴰ ⴰ ⴳ ⵓⵏⵎⴰⵍⴰ. ⵜⴰⵏⴰⴼⵓⵜ ⴰⴷ ⵜⵜⵓⵖⴰⵍ ⴷⵖⵢⴰ, ⵜⴰⵏⵎⵎⵉⵔⵜ ⵅⴼ ⵓⵚⴱⵕ ⵏⵏⵓⵏ.",
    suggestionsTitle: "ⵎⴰⵛⴰ ⵜⵔⵣⵣⵓⵜ ⵅⴼ",
    suggestions: [
      { label: "ⵜⴰⵙⵏⴰ ⵜⴰⵎⵣⵡⴰⵔⵓⵜ", href: "/" },
      { label: "ⵜⵉⵎⵢⵓⵔⵉⵏ", href: "/demarches" },
      { label: "ⵜⴰⵡⵉⵙⵉ", href: "/aide" },
      { label: "ⵉⵏⵖⵎⵉⵙⵏ", href: "/actualites" },
    ],
  },
  footer: {
    description:
      "ⵜⴰⴱⴱⵓⵔⵜ ⵜⴰⵏⴰⵎⵓⵔⵜ ⵏ ⵜⵏⴰⴼⵓⵜⵉⵏ ⵜⵉⴳⴷⵓⴷⴰⵏⵉⵏ ⵏ ⵜⴳⵍⴷⵉⵜ ⵏ ⵍⵎⵖⵔⵉⴱ ⵜⵙⵎⵓⵏ ⵜⵉⵎⵢⵓⵔⵉⵏ ⴷ ⵉⵏⵖⵎⵉⵙⵏ ⵉⵏⵚⵉⴱⵏ ⵏ ⵜⵎⴰⵡⴰⵙⵉⵏ ⴷ ⵜⵖⵔⵎⵉⵡⵉⵏ ⴽⵓⵍⵍⵓⵜⵏ.",
    ecosystem: [
      { label: "maroc.ma", href: "https://www.maroc.ma" },
      { label: "Idarati.ma", href: "https://www.idarati.ma" },
      { label: "Chikaya.ma", href: "https://www.chikaya.ma" },
      { label: "Service-public.ma", href: "https://www.service-public.ma" },
    ],
    columns: [
      {
        title: "ⵜⵉⵎⵢⵓⵔⵉⵏ",
        links: [
          { label: "ⵜⵓⴷⵔⵜ ⵜⴰⴳⴷⵓⴷⴰⵏⵜ", href: "/demarches?theme=etat-civil" },
          { label: "ⴰⵎⴰⴳⵏⵓ ⴷ ⵓⵜⵜⵓⵔ", href: "/demarches?theme=identite-voyage" },
          { label: "ⵜⵓⴽⴰⵔⵉⵏ ⴷ ⵉⵙⴰⵢⵙⵏ ⵏ ⵓⵙⵉⵜⵜⵍ", href: "/demarches?theme=vehicules-permis" },
          { label: "ⵜⵉⵙⵎⴹⴰⵍ", href: "/demarches?theme=impots-taxes" },
        ],
      },
      {
        title: "ⵜⵉⵖⵔⵎⵉⵡⵉⵏ",
        links: [
          { label: "ⵜⴰⵎⴰⵡⴰⵙⵜ ⵏ ⵓⵙⵎⵓⵜⵜⵉ ⴰⵎⵙⵙⵏⴳⴰⵍ ⴷ ⵓⵚⵍⵍⴰⵃ ⵏ ⵜⵏⴱⴰⴹⵜ", href: "/institutions/ministere" },
          { label: "ⵉⵏⵖⵎⵉⵙⵏ", href: "/actualites" },
          { label: "ⵜⴰⵡⵉⵙⵉ", href: "/aide" },
          { label: "ⴰⵔⵣⵣⵓ", href: "/recherche" },
        ],
      },
      {
        title: "ⵜⵉⵙⵎⵖⵓⵔⵉⵏ",
        links: [
          { label: "ⴰⵎⴰⵙⵙⵏ ⵏ ⵜⵎⵢⵓⵔⵉⵏ ⴳ ⵜⵉⵏⵜⵉⵔⵏⵉⵜ", href: "/aide" },
          { label: "ⴰⵙⵏⴼⴰⵔ ⴰⵏⴰⵎⴱⴰⵢⵍ", href: "/aide/application-mobile" },
          { label: "ⵉⵙⴰⴹⵓⴼⵏ ⵢⵕⵥⵎⵏ", href: "https://data.gov.ma" },
          { label: "ⵜⵉⵙⵎⵖⵓⵔⵉⵏ ⵏ ⵜⴱⴱⵓⵔⵜ", href: "/actualites/statistiques-portail" },
        ],
      },
    ],
    bottomLinks: [
      { label: "ⴰⵙⵓⴳⵣ ⵏ ⵓⵙⵉⵜ", href: "/plan-du-site" },
      { label: "ⴰⵣⴷⴰⵢ: ⵢⵎⵙⴰⵙⴰ ⵙ ⵜⴳⵣⵎⵜ", href: "/accessibilite" },
      { label: "ⵉⵏⵖⵎⵉⵙⵏ ⵉⵣⵔⴼⴰⵏⵏ", href: "/mentions-legales" },
      { label: "ⵉⵙⴰⴹⵓⴼⵏ ⵓⴷⵎⴰⵡⴰⵏⵏ", href: "/donnees-personnelles" },
      { label: "ⴰⵙⵡⵓⴹⵜⵓ ⵏ ⵉⴽⵓⴽⵉⵣ", href: "/cookies" },
    ],
    license: "ⵎⴰⵔ ⵓⵔ ⵢⵜⵜⵓⵙⴽⵜⵉ ⵢⴰⴹⵏ, ⵉⵏⵖⵎⵉⵙⵏ ⵢⵜⵜⵓⵙⵓⴼⵖⵏ ⴳ ⵓⵙⵉⵜ ⴰ ⵣⵎⵔⵏ ⴰⴷ ⵜⵜⵓⵙⵎⵔⵙⵏ, ⵎⴰⵔ ⵢⵜⵜⵓⵙⴽⵜⵉ ⵓⵙⵓⵔⵉⴼ ⵏⵏⵙⵏ.",
    newsletterTitle: "ⵇⵇⵉⵎ ⵜⵙⵙⵏⴹ",
    newsletterText: "ⴰⵡⵉ ⵉⵏⵖⵎⵉⵙⵏ ⵏ ⵜⵏⴰⴼⵓⵜⵉⵏ ⵜⵉⴳⴷⵓⴷⴰⵏⵉⵏ ⴷ ⵉⵎⴰⵢⵏⵓⵜⵏ ⵏ ⵜⴱⴱⵓⵔⵜ ⵙ ⵉⵎⴰⵢⵍ ⵏⵏⴽ.",
  },
};

export default content;
