/**
 * Icon layer — re-exports a curated Lucide set and adds direction-aware
 * arrows/chevrons that mirror automatically in RTL.
 */
import type { ComponentProps } from "react";
import {
  ArrowRight,
  ArrowLeft,
  ArrowUpRight,
  ArrowUp,
  ChevronRight,
  ChevronLeft,
  ChevronDown,
  ChevronUp,
  Check,
  X,
  Search,
  Menu,
  Globe,
  Sun,
  Moon,
  Monitor,
  Info,
  CircleCheck,
  TriangleAlert,
  CircleAlert,
  ExternalLink,
  Download,
  Share2,
  Printer,
  Copy,
  User,
  LogIn,
  LogOut,
  Mail,
  Phone,
  MapPin,
  Calendar,
  Clock,
  FileText,
  File,
  Paperclip,
  Upload,
  Filter,
  Plus,
  Minus,
  Eye,
  EyeOff,
  Lock,
  Star,
  Building2,
  Landmark,
  Home,
  MoreHorizontal,
  Loader2,
  CircleHelp,
  Accessibility,
  Languages,
  Bell,
  Settings,
  Trash2,
  Pencil,
  RefreshCw,
  ListFilter,
  Quote,
  BadgeCheck,
  ShieldCheck,
  Hash,
  Link as LinkIcon,
  CircleDot,
  Square,
  SquareCheck,
  Table as TableIcon,
  LayoutGrid,
  Rows3,
  Mic,
  Play,
  Pause,
  Volume2,
  Camera,
  Image as ImageIcon,
  Car,
  Stethoscope,
  GraduationCap,
  Briefcase,
  Scale,
  Wallet,
  Baby,
  HeartHandshake,
  Tractor,
  Plane,
  ScrollText,
  Fingerprint,
  QrCode,
  Send,
  MessageSquare,
  Newspaper,
  Megaphone,
  Users,
  ChartNoAxesColumn,
  Percent,
  Timer,
  Sparkles,
  Sprout,
  Waves,
  Sunrise,
  Mountain,
  Ship,
  Wifi,
  CreditCard,
  Receipt,
  Gavel,
  BookOpen,
  Handshake,
  Vote,
  Palette,
  Type,
  Ruler,
  Grid3x3,
  Shapes,
  MousePointerClick,
  Contrast,
  Layers,
  Component,
  PanelsTopLeft,
  Rss,
  Wheat,
  Droplets,
  Zap,
  Bus,
  Train,
  ClipboardList,
  CalendarCheck,
  SquareArrowOutUpRight,
  ArrowDown,
  Dot,
  CircleX,
  Ellipsis,
  ChevronsUpDown,
  BellRing,
  PhoneCall,
  Building,
  Flag,
  Award,
  Hourglass,
  SearchX,
  Inbox,
} from "lucide-react";

export type IconProps = ComponentProps<typeof ArrowRight>;

/* Direction-aware glyphs: "Forward" points to the reading direction. */
export function ArrowForward(props: IconProps) {
  return <ArrowRight aria-hidden className="dsm-flip-rtl" {...props} />;
}
export function ArrowBack(props: IconProps) {
  return <ArrowLeft aria-hidden className="dsm-flip-rtl" {...props} />;
}
export function ChevronForward(props: IconProps) {
  return <ChevronRight aria-hidden className="dsm-flip-rtl" {...props} />;
}
export function ChevronBack(props: IconProps) {
  return <ChevronLeft aria-hidden className="dsm-flip-rtl" {...props} />;
}
export function ArrowOutward(props: IconProps) {
  return <ArrowUpRight aria-hidden className="dsm-flip-rtl" {...props} />;
}

export {
  ArrowRight, ArrowLeft, ArrowUpRight, ArrowUp, ArrowDown, ChevronRight, ChevronLeft, ChevronDown, ChevronUp, ChevronsUpDown,
  Check, X, Search, SearchX, Menu, Globe, Sun, Moon, Monitor, Info, CircleCheck, TriangleAlert, CircleAlert, CircleX,
  ExternalLink, SquareArrowOutUpRight, Download, Share2, Printer, Copy, User, Users, LogIn, LogOut, Mail, Phone, PhoneCall, MapPin,
  Calendar, CalendarCheck, Clock, Timer, Hourglass, FileText, File, Paperclip, Upload, Filter, ListFilter, Plus, Minus, Eye, EyeOff,
  Lock, Star, Building, Building2, Landmark, Home, MoreHorizontal, Ellipsis, Dot, Loader2, CircleHelp, Accessibility, Languages,
  Bell, BellRing, Settings, Trash2, Pencil, RefreshCw, Quote, BadgeCheck, ShieldCheck, Hash, LinkIcon, CircleDot, Square, SquareCheck,
  TableIcon, LayoutGrid, Rows3, Mic, Play, Pause, Volume2, Camera, ImageIcon, Car, Bus, Train, Plane, Ship, Stethoscope,
  GraduationCap, Briefcase, Scale, Gavel, Wallet, CreditCard, Receipt, Baby, HeartHandshake, Handshake, Tractor, Wheat, Sprout,
  Droplets, Waves, Sunrise, Mountain, Zap, Wifi, ScrollText, ClipboardList, Fingerprint, QrCode, Send, MessageSquare, Newspaper,
  Megaphone, ChartNoAxesColumn, Percent, Sparkles, BookOpen, Vote, Palette, Type, Ruler, Grid3x3, Shapes, MousePointerClick,
  Contrast, Layers, Component, PanelsTopLeft, Rss, Flag, Award, Inbox,
};

export * from "./social";
